### ISSUE TITLE
Map locations showing Error

### ISSUE THREAD

**Issue by J3RMz** [Lailloken/Lailloken-UI#10]
![image](https://user-images.githubusercontent.com/19640331/154744531-facbaa73-2ce3-4577-b85e-14e2a7885a1a.png)
![image](https://user-images.githubusercontent.com/19640331/154744567-71614a61-fb3a-4167-bc86-a60c56b50fda.png)

**Comment by Lailloken** [comment]
whoops, will fix it asap.

**Comment by Lailloken** [comment]
> Forgot to commit updated db_archnemesis.ini 🙃

Yep yep, still getting used to GitHub.
