### ISSUE TITLE
Overlayke issue

### ISSUE THREAD

**Issue by Aldwew** [Lailloken/Lailloken-UI#100]
I've managed to get the frame the right size. How ever trying to right click to mark the entrance it says "scan the tablet first". If I understood correctly I scan the tablet by using the omni-key that is middle mouse. Doing that I get "custom highlight-key detcted: omni-key setup required". How do I setup the omni-key?

**Comment by Lailloken** [comment]
The omni-key has its own section in the settings menu, where it can be rebound to a different key or where a specific setup has to be done if certain in-game keybinds have been changed. The script has detected that you have rebound the item-highlighting to something other than ALT, so you have to specify which key. There's a text-box in the omni-key section of the settings menu into which you have to type that key. If it's just a single key, type that in; if it's a modifier key (shift, control, etc.), you have to type it out.

This is a workaround that I implemented somewhat recently, so it's not very smooth yet. If you encounter any problems in getting this to work, let me know.

**Comment by Aldwew** [comment]
I have not rebound the item-highlighting, also it won't let me specify lalt.

**Comment by Lailloken** [comment]
Okay, that's strange. Could you go to the folder where loot-filters are stored and open the file 'production_Config.ini' in a text-editor? There should be a line "highlight=". I need to know which number is assigned to that because something is triggering custom-keybind detection.

**Comment by Aldwew** [comment]
highlight=18

**Comment by Lailloken** [comment]
Okay, there seems to be an issue with reading the PoE config-file because highlight=18 means highlighting is bound to ALT. I had similar issues in the past where the first line was unreadable, but it seems your entire file cannot be read.

You can download this [hotfixed version](https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/dev.zip) which ignores the custom-keybind detection for now. I will implement a proper fix when I get home. Let me know if that fixes it.

**Comment by Lailloken** [comment]
I have just released v1.28.3 with changes to the omni-key and custom-keybind detection. I would suggest resetting the omni-key settings if your Alt- and C-keys in game are default. Otherwise, go through the omni-key settings and set things up as instructed there.
