### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by Lonami** [Lailloken/Lailloken-UI#107]
Hey, the features showcased in the README look amazing. It sure has grown a lot ever since I first saw this on the PoE subreddit which is great to see.

But I couldn't find a mention to the project's license anywhere. Would you be willing to add a license to the project? No license essentially means "my code, don't touch it, don't use it for your own", which is unfortunate because I would've liked to fork it to tweak it to my needs (specially since the README says "I will not be taking code input or optimizations from people").

(I mean, I can still do that, but it wouldn't be very nice. The other option is clean-room reimplementation which is a pain.)

**Comment by Lonami** [comment]
I see https://github.com/Lailloken/Lailloken-UI/commit/83a849318b532f9c83df06ed1fb843fe70659d15 now. Thanks!

**Comment by Lailloken** [comment]
> I would've liked to fork it to tweak it to my needs

If you think these tweaks could be beneficial for a broader user-base, please share these with me. I could always use some feedback on user experience.

> specially since the README says "I will not be taking code input or optimizations from people"

It just means that I don't want things like these to happen: "There's a problem with XYZ, here's the code to fix that." Or "this area needs improving, here's the code." I want to learn things organically and come up with my own solutions/improvements to problems.

**Comment by Lonami** [comment]
> If you think these tweaks could be beneficial for a broader user-base, please share these with me. I could always use some feedback on user experience.

Ah, no, I just thought it would be fun to fork and [RIIR](https://transitiontech.ca/random/RIIR). Not sure if I'll actually do this, but it did sound like a fun project which is why I wondered about the lack of license.

> I want to learn things organically and come up with my own solutions/improvements to problems.

That's fair! I think if others were to contribute code you didn't think of, it's also a good way to learn. I was only wondering about the license, I'm totally okay with any other rules regarding contribution.
