### ISSUE TITLE
PoE config file

### ISSUE THREAD

**Issue by atie101** [Lailloken/Lailloken-UI#122]
Hello, on start script, got error - Cannot read the PoE config-file. Try fresh install, run as administrator.

**Comment by Lailloken** [comment]
Did the script ask you to locate the PoE-config file the first time you started it, or did the error message show immediately?

The script tries to read the PoE-config to know if the client is running in windowed mode or not. If it can't find it, it asks the user to locate it.

**Comment by Lailloken** [comment]
I have implemented a potential fix: https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/dev.zip. Please report back if that works for you.

**Comment by atie101** [comment]
The first installation, when trying to run, an error appears  (no regular error, only window with message) and then the script crashes. If try dev zip 
![obrazek](https://user-images.githubusercontent.com/26604808/204506752-2d52f62d-ac92-4e7b-ae93-e97e1f4fc624.png)

**Comment by Lailloken** [comment]
I missed something before, should be fixed now. Re-download the dev.zip

**Comment by atie101** [comment]
Now got this. I play all time in windoved fullscreen.
![obrazek](https://user-images.githubusercontent.com/26604808/204514231-0b2c99c0-11ef-47f7-a101-8c1a9d98fb43.png)
indoved fullscreen.

**Comment by atie101** [comment]
Its on me side. I run script as diferent user. Now work well. Thanks for help.

**Comment by Lailloken** [comment]
You're welcome, and thanks for reporting this issue. Have fun with the tool.
