### ISSUE TITLE
Item-info window never appears

### ISSUE THREAD

**Issue by lherron** [Lailloken/Lailloken-UI#125]
I'm not able to ever see any item-info popup.  The script is running, I can see the config menu.  I have calibrated.

The only other window I see other than setup window is when I click on "Betrayal-Info" configuration.

Resolution is set to 2560x1440 (what my monitor is using).

Not sure what else to try!  Any ideas?  Thanks!

**Comment by Lailloken** [comment]
What happens if you click the middle mouse-button normally on an item? Do you get the context-menu?

**Comment by Lailloken** [comment]
I'll soon be offline to get some sleep, so here's a few things you can try to troubleshoot:
- as I mentioned, clicking the middle mouse-button on various items should trigger a context-menu. If that works, we at least know the omni-key itself is working

- item-info tooltips are triggered by long-clicking the middle mouse-button on supported items. If there's a problem, an error message should pop up near the cursor, e.g. if the item is not supported or if the script has trouble copying the item's text from the client. If neither the tooltip itself nor an error message shows up, it's possible long-presses of the middle mouse-button are not recognized correctly.
- if none of the above works, you could try re-binding the omni-key to something other than middle mouse-button, e.g. the 0-key (just to test it). Hover over different items and (long-press) the 0-key to see if anything changes in its behavior.

**Comment by lherron** [comment]
Thanks so much for the response!  Here are more details:

I'm not seeing any AHK tooltip (small white box) when I short-click or long-click (although I did see that when I didn't have the screen captures configured.)

I tried re-binding omni-key and item-key, no luck.

When I short-click I do not get the context menu.  However when I short-click the "LLK-UI" box in the top-left disappears.  When I short-click again, the LLK-UI box in top-left reappears.  Also, 

It makes me think the click is registering and it's trying to paint the window, but either it's painting it offscreen or it's not painting at all.  Also the in-game item info box disappears when I press omni-key, as if the PoE window is losing focus.

**Comment by lherron** [comment]
For whatever reason, on my machine alt-ctrl-c always returns an empty clipboard (even with LLK turned off).  This may be because I have bindings for Alt-1 thru Alt-4, really not sure.

This code:

```
If (alt_modifier != "")
	SendInput {%alt_modifier% down}^{c}{%alt_modifier% up}
Else SendInput !^{c}
ClipWait, 0.05
If (clipboard != "")

```

Always ends up with an empty clipboard.  I never see any tooltip for an error, so not sure what state the script is in at that point.  (I do see the "need to set advanced key" tooltip error if I remove the ! and send only ctrl-c.)

I worked around this by changing my in-game highlight key to 'x' and setting LLKUI highlight key to 'x' in configuration.  Now all is well.

Thanks!
