### ISSUE TITLE
Cull indicator

### ISSUE THREAD

**Issue by stoyicker** [Lailloken/Lailloken-UI#127]
Hi,

first, thanks for your software. I was wondering if it'd be possible to draw a cull indicator over health bars. Basically, if I'm not mistaken, all mob health bars take the same amount of space and are drawn on the same position on the screen. So it should be possible to calculate where the 10% would be to draw a line there so that if we see health fall below that line we know we can cull. Right?

**Comment by Lailloken** [comment]
Yes, it's possible. While I don't personally like this specific idea, I could implement a more general feature to load images and overlay them over the client. This way, the user may do whatever they want.

Thanks for your suggestion.
