### ISSUE TITLE
[REQUEST] Setting the display position of the priority list

### ISSUE THREAD

**Issue by ysalpha2021** [Lailloken/Lailloken-UI#13]
Hi, I'm using 1.17.0-beta.
Please make it possible to change the display offset position of the priority list in the config.ini setting.

This is because it overlaps with the description of the material as shown in the screenshot.
![bad2](https://user-images.githubusercontent.com/95667621/154824509-a8b4c9c5-9eaf-402c-aa7a-57624901a970.png)

In my case, I want it to appear in the following position
![good2](https://user-images.githubusercontent.com/95667621/154824511-a73162a8-e522-4c37-b6f7-18c67df1e87b.png)

**Comment by Lailloken** [comment]
I changed it to the panel automatically hiding while hovering icons. Please test it and give me your feedback.

**Comment by ysalpha2021** [comment]
Thank you!
I'll test with latest-version for a while(for a day or so).

**Comment by Lailloken** [comment]
Yeah, I wanted to check how many rows are affected for every resolution individually but haven't found the time yet. I implemented the current behavior by using screenshots I still had, which was less work.
