### ISSUE TITLE
Gwennen Regex not working?

### ISSUE THREAD

**Issue by blake-sherrill** [Lailloken/Lailloken-UI#130]
Hopefully this isn't just me. But I cannot get the regex for gwennen to work properly.

The screen check for gwennen passes. 
When I click the omnikey it says "no regex string saved". 

Vendor works great. Stash works. Just not gwennen.

**Comment by Lailloken** [comment]
You need to long-click the omni-key to open a window into which to paste the Gwennen-specific string. The gwennen strings and general vendor strings are two separate features, Gwennen's being older.

Now that I think about it, I should probably merge them and add Gwennen as a use-case for general search-strings, which would allow for more than one Gwennen regex.

**Comment by blake-sherrill** [comment]
Ok awesome figured it out. Sorry I tried to find instructions for it, but never could find any. Thanks!
