### ISSUE TITLE
"Line Text: Switch item_type" Error

### ISSUE THREAD

**Issue by toyomatt84** [Lailloken/Lailloken-UI#132]
Hello, I was trying to setup and use your tool, but when trying to run the "Lailloken UI.ahk" I get an error:

Line Text: Switch item_type
Error: This line does not contain a recognized action.

Then the program shuts down.

Should I be placing the folder somewhere special?
I am playing PoE on the PoE client, not Steam.

**Comment by Lailloken** [comment]
I think the AHK installation on your system might be outdated.

**Comment by toyomatt84** [comment]
> I think the AHK installation on your system might be outdated.

Version 12900 according to the download.
