### ISSUE TITLE
[Kakao Client] There is no Leveling & Mapping Tracker in the UI Settings menu tab

### ISSUE THREAD

**Issue by sniper-sin** [Lailloken/Lailloken-UI#133]
![image](https://user-images.githubusercontent.com/83152730/206500038-1ee13173-084d-4b0d-b13b-249f475e969c.png)

There is no Leveling & Mapping Tracker in the UI Settings menu tab.
I'm using Lailloken-UI-1.29.0 and I've checked that the leveling tracker.ahk and map tracker.ahk files exist in the modules folder, but they don't appear in the settings menu tab.

**Comment by sniper-sin** [comment]
=

> These are hidden if the script can't find the client.txt log-file in the game's folder at startup. Which client are you using, and could you check the logs folder in your PoE installation? There should be a client.txt file.
> 
> EDIT: these features are reliant on that file.

I was expecting that to be the problem, thank you so much for your reply!! 
What if my log file is not "C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\client.txt" but "C:\Daum Games\Path of Exlie\logs\KakaoClient.txt"
If so, need I modify the script from "logs\client.txt" to "logs\KakaoClient.txt"? 
Or do I need to modify the folder path of the log file together?

**Comment by Lailloken** [comment]
That should fix the issue of not finding it, though I don't know if everything works fine after that. I didn't know there were different log files. If it does indeed work, please report back so I can implement an official fix for this situation.

**Comment by rlehdlaek** [comment]
Same problem with using"Kakao client" it is Korean version using different service provider but everything is the same with global version excpet file location. Just like him everything works but those leveling&mapping categories are not showing for me neither.

**Comment by sniper-sin** [comment]
> That should fix the issue of not finding it, though I don't know if everything works fine after that. I didn't know there were different log files. If it does indeed work, please report back so I can implement an official fix for this situation.

I modified the script to allow users to run "Kakao client", it works fine. Thanks for the help :D

https://drive.google.com/file/d/1BAk0_cb1RWiNiz77hma3L1jrTknN67Nz/view?usp=share_link

**Comment by Lailloken** [comment]
Thanks for confirming that it's only the file-name that's different. I'll implement official support in the next version.
