### ISSUE TITLE
Leveling tracker shows success on import but doesn't show guide info

### ISSUE THREAD

**Issue by Cllyde** [Lailloken/Lailloken-UI#136]
I downloaded the new version from today, ran the script, and in the Leveling Tracker section, clicked Generate Guide. I imported my build (Pohx RF Jugg from his website) and checked off my progress on the website, before exporting and then importing with the LLK Import Guide button. It shows success, but the progress percentage that said 0% disappears, and I then get a 'no imported guide' message when left clicking the book icon, and the attached error message when right-clicking it.
![Lailloken-leveling tracker error](https://user-images.githubusercontent.com/2433504/206562606-62f0a8b1-52a6-4d71-8d55-84d71ffbdb11.png)

**Comment by Cllyde** [comment]
placing the cursor behind the r in line 550 of leveling tracker.ahk and hitting backspace twice to just remove the r will let me right-click the book icon, but no characters are found, and still cannot get the guide to import correctly. After doing this I completely wiped the LLK folder and reinstalled/re-started the script and am having the same issue as originally posted.

**Comment by Cllyde** [comment]
I do run Path of Building and Awakened POE Trade. So I tried shutting down PoE, LLK, and both of those other tools, then renamed the "C:\Program Files (x86)\Steam\steamapps\common\Path of Exile\logs\Client.txt" file to Client_backup.txt.
After those steps I started up PoE, then LLK, and tried to enable the Leveling Tracker with the default route (no imported build, but disabled league start and library checkboxes), I still get 'no imported guide' and the error about the r on line 550 in leveling tracker.ahk

[route-info.txt](https://github.com/Lailloken/Lailloken-UI/files/10189618/route-info.txt)
[pob-data.txt](https://github.com/Lailloken/Lailloken-UI/files/10189620/pob-data.txt)

**Comment by Lailloken** [comment]
Yeah, that's the build guide I tested earlier. Could you open the ini folder of the script and open the 'leveling guide.ini' file? That's where the individual steps and the progress are saved. Is there anything unusual about the contents of that file?

I also have to hit the bed right now, but I'll check back first thing in the morning.

**Comment by gabrielhurley** [comment]
I'm having the same exact issue. There is no leveling guide.ini file anywhere in the folder. Looks like maybe that file/data is not getting written for some reason.

**Comment by Lailloken** [comment]
> I'm having the same exact issue. There is no leveling guide.ini file anywhere in the folder. Looks like maybe that file/data is not getting written for some reason.

Some people have write-permission issues that prevent them from setting up the image-checks. Maybe running the script as administrator would help, I'm not sure. A temporary fix could be creating said file manually as a blank ini-file and see if that fixes it. Though that would be just a temporary fix, and the problem would certainly come up again somewhere else.

**Comment by Cllyde** [comment]
It must be something with folder security. I also could not find that file, and ended up trying to run LLK from C:\temp instead of Program Files and now it is actually importing the build successfully. Characters for gear tracker (right-click book icon) are still not importing after restarting LLK multiple times so I'm not sure what to check for that yet.

**Comment by Lailloken** [comment]
> Characters for gear tracker (right-click book icon) are still not importing after restarting LLK multiple times so I'm not sure what to check for that yet.

Shoot, I got distracted by that other problem. The script scans the client.txt for recent characters by looking for the level-up message that is logged there. You probably have to level up once and then restart the script to make it find the character. Sorry about that, things are pretty hectic right now due to higher traffic.

**Comment by Lailloken** [comment]
> * Add a check for write permissions on the directory and raise an error to the user if the check fails.

Yes, it's included in the next release. Thanks for confirming, I couldn't replicate it whatsoever.
