### ISSUE TITLE
Mouse Cursor freezing while moving

### ISSUE THREAD

**Issue by igloo15** [Lailloken/Lailloken-UI#147]
When I have the software running my mouse cursor freezes sometimes and then jumps to another spot after a couple of seconds. Turning off the software makes it not happen. 

It is some how related to click as it occurs just after clicking sometimes. Not every time though. Either way I turned off my mouse software and it still is happening.

I am on Windows 10 and using a Logitech G903 mouse

**Comment by Lailloken** [comment]
Could you try disabling "background pixel-checks" in the screen-checks menu? There is an extremely rare case where the screen-reading causes these hitches. I think you're the second case in almost 10 months.

**Comment by igloo15** [comment]
I tried that but it still doing it. I also noticed that sometimes after clicking it thinks my mouse button is still down and my character just follows my cursor around. 

I also noticed mouse wheel is strangely laggy. In passive screen zooming in and out hitches.

**Comment by Lailloken** [comment]
Does it happen immediately after starting the tool, or does it take time to exhibit this behavior? And did you turn on any optional features, or is everything at default settings?

**Comment by igloo15** [comment]
I just have the level tracking on. It starts immediately as soon as I start script. It only happens in game so if I alt tab don't notice anything. I am running the latest 1.29.2. I tried a couple of things like turning of the LUI button thing. I turned off background pixel checks. 

It feels like the release of my mouse button is not being detected sometimes. So its detecting a mouse hold when I just clicked once.

**Comment by igloo15** [comment]
I did screen calibrations as well

**Comment by igloo15** [comment]
The Client.txt file is 54MB in size. That seems pretty large for a text file.

**Comment by Lailloken** [comment]
You could try renaming it to keep it as a backup. You have to close the client and the script to get file-access to it. Restarting the client will create a new file, and you can check if that helps. If you're also using my gear-tracker, you'll either have to revert the file change or copy a line over that contains the "X is now level Y" because the script uses that to determine which characters are available for tracking.

**Comment by igloo15** [comment]
Yup that did it. Renaming the Client.txt and restarting everything and now no mouse freezing.

**Comment by Lailloken** [comment]
Glad to hear that, enjoy.

**Comment by pheamit** [comment]
I have a similar issue, with the mouse cursor movement becoming laggy and choppy when I press and hold any of the "QWERT" buttons. The Client.txt tech didn't help, unfortunately.

**Comment by Lailloken** [comment]
@pheamit That is really strange, I have never heard of something like that. Is it really only QWERT? Could you test other letter-keys?
