### ISSUE TITLE
Include file "data\Class_CustomFont.ahk" Cannot Be Opened Error

### ISSUE THREAD

**Issue by ckjustin** [Lailloken/Lailloken-UI#149]
Not sure if I'm doing correct but when I try to run the script open with AHK, it shows this error.
![Screenshot 2022-12-10 083559](https://user-images.githubusercontent.com/66343901/206819313-640b631f-bbe0-4741-a0ea-6423f1e319b0.png)

**Comment by killtastrophe** [comment]
NVM found fix
