### ISSUE TITLE
Switch A_LoopField

### ISSUE THREAD

**Issue by andy015** [Lailloken/Lailloken-UI#151]
Hey, I keep getting this error message when trying to run the .ahk

![aaadda5a6f2e49dcab1e4e5a0ea253e3](https://user-images.githubusercontent.com/82028337/206859044-6deb3b66-31e6-429a-9de4-e9a94dbfca55.png)

**Comment by Lailloken** [comment]
Update your AutoHotkey

**Comment by andy015** [comment]
Thanks
