### ISSUE TITLE
[INFO] Frequent Problems & Errors

### ISSUE THREAD

**Issue by Lailloken** [Lailloken/Lailloken-UI#152]
- **AutoHotkey Error: "This line does not contain a recognized action."**
  - solution: Update the AutoHotkey installation on your system

- **AutoHotkey Error: "#Include file data\Class_CustomFont.ahk cannot be opened."**
  - should be resolved, starting from v1.30.4-hotfix2

  - solution 1: Correctly extract the script from the ZIP-file
  - solution 2: When launching the tool via any method other than double-clicking the .ahk-file (e.g. any form of CLI), make sure to explicitly state the correct working directory (thanks to WildGenius)

  - solution 3: Create a shortcut on the desktop for the "Lailloken UI.ahk" file and use that to launch the script (thanks to Aervanath in #217)

- **"The script could not create some required folders"**
  - solution 1: Follow the instructions and move the script folder somewhere else or run it as administrator

  - solution 2: Follow the instructions in this [wiki article](https://github.com/Lailloken/Lailloken-UI/wiki/Known-Issues-&-Limitations#error-message-write-permission-issues)

- **"The game-client is set to exclusive fullscreen."**
  - solution 1: Set the game to windowed mode, click 'save'. Set the game to windowed fullscreen mode, click 'save'. Restart the script.

  - solution 2: Open the 'Production_config.ini' file (it's in the same folder as lootfilters) and edit these lines to: "fullscreen=false" and "borderless_windowed_fullscreen=true"
    - if you're running PoE with a different Windows user-account, you have to follow these steps: [wiki article](https://github.com/Lailloken/Lailloken-UI/wiki/Known-Issues-&-Limitations#running-poe-on-a-limited-user-account)

- **The item-info tooltips only show for a split second and then vanish**
  - solution: re-calibrate the inventory screen-check

**Comment by ckjustin** [comment]
@Lailloken thanks for putting this up, for the include file data\Class error, when you say correctly extract the script from the ZIP-file what does that mean?

**Comment by WildGenius** [comment]
For what it's worth, the "#Include file data\Class_CustomFont.ahk cannot be opened." error can be 100% replicated on the latest 1.1 AHK by trying to start the (extracted) script using the PowerShell `Start-Process` (whether via Terminal or Playnite Scripts).

**Comment by lordspirit** [comment]
Any other fix for CustomFont.ahk cannot be opened error ? Would love to test this during 3.12 league.

**Comment by lordspirit** [comment]
it was weird because I've downloaded the latest AHK version and then script asked me to 'upgrade' to 1.36 version or something like that. However, now its working after a reboot! thanks sir. I'll try it now. props for your work

**Comment by liqito** [comment]
Getting an antivirus flag of the ahk file. 
![image](https://user-images.githubusercontent.com/41124174/230660859-c3532283-0e79-4997-bc81-6daba99cb18a.png)

**Comment by Lailloken** [comment]
@liqito You'll have to cross-check with additional scanners, or do some research into what IDP.Generic means because I can't help you in this situation. Ultimately, you'll have to decide for yourself if you want to run the script. All I can say is that it's open-source, distributed as source-code, and the same code I'm running myself.

**Comment by GonePh1shing** [comment]
To fix the `"#Include file data\Class_CustomFont.ahk cannot be opened."` error when launching the script from within another AHK script, you can do one of the following to resolve the issue:

Option 1:
Set the working directory of the first AHK file to the folder containing the script, then run the script
```
SetWorkingDir, C:\path\to\your\working\directory
Run, C:\path\to\your\script.ahk
```

So, if your script is located in `C:\Users\%UserName%\Documents\POE Tools\Lailloken-UI`, this becomes:
```
SetWorkingDir, %UserProfile%\Documents\POE Tools\Lailloken-UI
Run, %UserProfile%\Documents\POE Tools\Lailloken-UI\Lailloken UI.ahk
```

Option 2:
Use the 'WorkingDir' parameter in the 'Run' command when calling the script
```
Run, C:\path\to\your\script.ahk, C:\path\to\your\working\directory
```
As above, this becomes:
```
Run, %UserProfile%\Documents\POE Tools\Lailloken-UI\Lailloken UI.ahk, %UserProfile%\Documents\POE Tools\Lailloken-UI
```

**Comment by Lailloken** [comment]
@GonePh1shing Yes, I was also considering including a launcher file that would launch the main script with a defined working directory. But I'm hesitant because I think this could potentially trigger anti-virus software because of behavior patterns.

**Comment by GonePh1shing** [comment]
@Lailloken Yeah, probably best to just leave it as-is. It's an edge case that the majority of users won't ever encounter. I see you've mentioned in the wiki to include the correct working directory, which is probably good enough for most users that are launching indirectly to figure out and resolve the issue.

The only thing extra you may ever want to do is include a link to instructions already provided in this thread on how to do so from AHK and Powershell, which are the two most likely ways of launching the script indirectly; Perhaps on its own Wiki page to prevent the FAQ from becoming cluttered?
