### ISSUE TITLE
Item Info pop-up flashes briefly when using the omni key.

### ISSUE THREAD

**Issue by Shinzoushein** [Lailloken/Lailloken-UI#153]
I had this problem yesterday for most of the day. It appeared to fix itself, though I don't recall how or why. Today it is happening again. When I press the omni key on a rare the Item Info popup flashes briefly.

**Comment by Lailloken** [comment]
Try recalibrating the inventory screen-check. The 3.20 update changed the UI colors a bit, which means the calibration data is out of date. I forgot to mention that in the Frequent problems thread.
