### ISSUE TITLE
serach-strings ©

### ISSUE THREAD

**Issue by Newbrn** [Lailloken/Lailloken-UI#154]
Hello everything is fine?

I'm having the following bug, when using the omini key to activate serach-strings I'm only receiving the © character in the search bar instead of the pop up with the serach-strings options

**Comment by Lailloken** [comment]
Do you have multiple search strings set up? If only one search-string is set up, it will execute directly instead of showing the menu (as a shortcut). Which kind of search-string were you trying to set up, and what text did you put into them?

**Comment by Newbrn** [comment]
https://user-images.githubusercontent.com/36965243/206898435-43771b9c-caad-4f1a-b03d-7fe47e455fd6.mp4

I apologize for my lack of detail in reporting the problem... I appreciate your enormous patience in asking for details.

follow video with example, it works for example popup bar of information of items... but for search in chests and sellers, it sends the character mentioned only...

**Comment by Lailloken** [comment]
Sorry for my late reply, I didn't get a notification on my phone. Could you send me a screenshot of the contents in this file: 'ini\stash search.ini'?

**Comment by Newbrn** [comment]
this is as follows, I also attached the file...


[Settings]
stash=(01_|_011),(02_|_022),(03_|_033),
vendor=(01_|_011),(02_|_022),(03_|_033),
[01_|_011]
enable=1
string 1=""item level: 83""
string 1 enable scrolling=1
string 2=""
string 2 enable scrolling=0
[02_|_022]
enable=1
string 1=""item level: 26""
string 1 enable scrolling=1
string 2=""item level: 36""
string 2 enable scrolling=1
[03_|_033]
enable=1
string 1=""item level: 81""
string 1 enable scrolling=1
string 2=""item level: 51""
string 2 enable scrolling=1

![image](https://user-images.githubusercontent.com/36965243/206906580-44653ff2-a21d-4956-bcbc-0fc3c64fc591.png)

**Comment by Lailloken** [comment]
That is strange. If I paste that into my ini-file, it works without problems. Could you go to 'screen-checks' in the settings menu, click 'open img folder', and send me a screenshot of the folder contents?
![image](https://user-images.githubusercontent.com/61888437/206908199-17f3851c-8db7-4d60-b595-56b4c99a46e3.png)

It looks like the script is maybe pasting the Gwennen string, but I'm not sure.

**Comment by Lailloken** [comment]
That is strange. If I paste that into my ini-file, it works without problems. Could you go to 'screen-checks' in the settings menu, click 'open img folder', and send me a screenshot of the folder contents?
![image](https://user-images.githubusercontent.com/61888437/206908199-17f3851c-8db7-4d60-b595-56b4c99a46e3.png)

It looks like the script is maybe pasting the Gwennen string, but I'm not sure.

**Comment by Newbrn** [comment]
Of course I can send it to you, I'm really having trouble and I've tried everything... it just keeps sending © instead of the popup...
maybe some problem with language pt-br on my keyboard?

![image](https://user-images.githubusercontent.com/36965243/206914173-c104ec77-a71c-494f-9c56-00bcdc7c51f2.png)
![image](https://user-images.githubusercontent.com/36965243/206914205-08e304f2-57bb-4e0d-9979-ceef3a1d6877.png)

**Comment by Lailloken** [comment]
> maybe some problem with language pt-br on my keyboard

Maybe. The script sends ALT+CTRL+C first, then CTRL+F+V. Are these used for shortcuts in the PT-BR layout?

**Comment by Newbrn** [comment]
the type of input on the keyboard really makes a difference, I have an international amarican keyboard and using the international standard of the united states I get ©, using pt br I get ₢.

Is there any possibility of not using the CTRL? I believe this key is associated with some shortcuts for characters not present on the keyboard.

![image](https://user-images.githubusercontent.com/36965243/206918376-16248aa9-be78-44ab-a595-0f197dd0533f.png)

**Comment by Lailloken** [comment]
Oh, interesting. Actually, you don't have to click into the search-field first for it to work. You can click anything within the game's UI (e.g. an empty field in the stash/inventory). It's possible that the input of these special characters interrupts the search-strings menu.
![image](https://user-images.githubusercontent.com/61888437/206918664-c09270b7-e0dd-4d96-8f05-7237e8977428.png)

**Comment by Newbrn** [comment]
when I press the omini-key in the inventory I end up not getting anything because there is nowhere to insert those weird characters besides a textbox. But when I use the omini on an item, the pop up explodes normally.

I come to the conclusion that the hotkey ALT+CTRL+C is the culprit, when I press it manually it also inserts ©

![image](https://user-images.githubusercontent.com/36965243/206919005-01ac1903-41ed-423b-b928-1312f4be42d6.png)

**Comment by Lailloken** [comment]
Okay, I hoped there was a difference between just pressing the combination, and sending it into a text-field. There is a fix you can use: In the omni-key section, there is a hotkey-field for "omni-key (items)". You can bind a key that is exclusive for items. This means you use this new hotkey for any feature that is connected to items (e.g. the context-menu in the last image you posted), and the regular omni-key for anything else (search-strings, betrayal, etc.).

This is normally a fix for something different, but I think this should work for you as well. I don't think there is another way.

**Comment by Newbrn** [comment]
really without success, I tried several other shortcuts in the configuration... but as it sends ALT+CTRL+C and this hotkey is linked to a character, it won't work...
I appreciate the attention and thank you!

**Comment by Lailloken** [comment]
If you split the omni-key, the main one won't send anything -- only the one for items. That's the whole point of the fix. It's for people who have something bound to the C-key and need the script to stop pressing C.

**Comment by Lailloken** [comment]
For some reason, it works for me on the PT layout, even without fixes.

![image](https://user-images.githubusercontent.com/61888437/206921170-562d9962-be0c-49b1-b601-02cb3da19927.png)

**Comment by Newbrn** [comment]
I tried to change the shortcuts in the settings where you mentioned and also without success. 
With your last post it seems even more complicated... I don't know what's going on. 
If you want to close the bug report... no problem! thank you again.
