### ISSUE TITLE
map tracker : "Error in #include file" with contracts

### ISSUE THREAD

**Issue by phil00** [Lailloken/Lailloken-UI#157]
Contracts seems to cause problems when finishing the tracking of the loot of a map.

Here's the error :

![image](https://user-images.githubusercontent.com/755269/207091633-1f195627-8b73-4cc5-b909-be4356b63567.png)

Thanks

**Comment by Lailloken** [comment]
Thanks for reporting. It's an oversight with magic contracts because their item-information is structured differently. I'll fix it shortly.

**Comment by Lailloken** [comment]
Fixed in v1.29.3
