### ISSUE TITLE
Item stats closing

### ISSUE THREAD

**Issue by PergonGER** [Lailloken/Lailloken-UI#165]
Hey,

got the issue that the item-info window directly closes upon opening.
Tried a new install, got the latest build.

Any ideas how i might fix it?

**Comment by Lailloken** [comment]
It automatically closes whenever the inventory closes. Your inventory pixel-check probably needs to be recalibrated.

**Comment by PergonGER** [comment]
Thank you, solved!

Am Fr., 16. Dez. 2022 um 12:25 Uhr schrieb Lailloken <
***@***.***>:
