### ISSUE TITLE
Icons on undesired class-specific mods

### ISSUE THREAD

**Issue by stefaz** [Lailloken/Lailloken-UI#176]
Just a small issue that I noticed in my game that is different from the behavior described in the last release notes (1.29.5):
It states that the icons are removed when a mod is tagged as undesired and according to the screenshot from example 1 (the regular/rune daggers) this should also work for class-specific undesired mods. 
For me that only works with general undesired mods (short right-click / red overlay) but not with the class-specific ones (magenta overlay) - there the icon stays as you can see in the screenshot, even after refreshing the tooltip.

![image](https://user-images.githubusercontent.com/12692375/209424714-d0c21b81-2289-4753-a38a-352f640f9f2d.png)

**Comment by stefaz** [comment]
well, it seems the removal of the icons is now no longer working for me at all. I suspect this feature breaks when the undesired mod is tagged as desired on another item class, need to test this further.

**Comment by Lailloken** [comment]
Huh, that's strange. I downloaded the latest release and extracted it into a separate folder in order to test a clean install, and it works as expected. Code-wise, it also shouldn't matter if it's class-specific or global. The background behind the phys icon turns red, which indicates correct behavior. If that's red, the icon should also be hidden -- these two have the same conditions (override enabled in the settings, modifier is undesired). Maybe it's a bug within AHK, so updating may fix it.

I'll look into it further once I'm back from walking the dog.

**Comment by Lailloken** [comment]
I think I found the issue: there was an accidental asterisk in the code, so some modifiers were saved/removed from "profile X*" instead of just "profile X". I'll release a hotfix shortly.

**Comment by stefaz** [comment]
yeah, thanks - I also saw this when looking at the .ini files and wondered what it is for ;) does that mean I can remove that section in the .ini-file?

**Comment by Lailloken** [comment]
I really shouldn't code while in voice-chat (asterisk is my mute button), sorry about that. The hotfix should remove those entries, but you can remove them manually if you want.

Thanks for reporting this issue, I hope nothing else is bricked.

**Comment by stefaz** [comment]
so, I just tested the hotfix and at first I thought it's still not working until I figured that hiding the icons only works when "Blacklisting overrides Tier & iLvl Color" is enabled - I guess that is intended and I missed this detail in the release notes/Wiki.

But I think that option is not working as intended since I have the following behavior:
- with "blacklisting override" disabled: setting a mod as undesired still shows the icon but sets the color to T6
- with "blacklisting override" enabled: setting a mod as undesired hides the icon and sets the color to T6

shouldn't the "disabled" setting leave both icon and color untouched?

**Comment by Lailloken** [comment]
Ah, you're right. That explains why the icons behaved so weird. The background turned red (bug), which made me assume the override was enabled. There's a missing check of the override-setting, so the background of the icons will always turn red if undesired. Another hotfix incoming...
