### ISSUE TITLE
(Request/Suggestion) Quality Set Calculator

### ISSUE THREAD

**Issue by RobertoJKN** [Lailloken/Lailloken-UI#179]
Hello! Would it be possible to make a script to check the best possible Quality [Weapons/Armours/Flasks/Gems] Sets to vendor? Essentially what [this](url) tool does, but without having to check item by item while inputting each individual value into the tool. The script could either highlight combinations(?) or it could allow you to copy all quality values from all gear in that stash (so a player could make a stash for quality weapons, another for armours, etc.), or perhaps from that type of item ([Weapons/Armours/Flasks/Gems]) so one could easily paste those values in the tool linked above.

**Comment by Lailloken** [comment]
I wanted to implement stash features but I have put that on hold since GGG publicly announced that using POESESSID in 3rd-party tools is bad practice. There currently is no alternative way to access stashes, so I'll have to wait and see if anything changes about that.

**Comment by RobertoJKN** [comment]
Thank you for the fast response. That is rather unfortunate, hopefully a solution shows up eventually.
