### ISSUE TITLE
Weirdness with max item levels in item info

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#194]
Item info popup has a field showing the item's level and maximum level relevant for crafting. Non-rare Heist rogue items (all types) always display max level 86 while rare ones properly show lower numbers (83-84).
![изображение](https://user-images.githubusercontent.com/6707627/222918694-4d4dbed1-265f-4e24-a382-acb8881cf89d.png)
![изображение](https://user-images.githubusercontent.com/6707627/222918714-a8b45c84-3c19-46b1-9fa1-862c662dccc6.png)

**Comment by Lailloken** [comment]
Huh, it actually happens with every magic item, it seems. I changed something a while ago to make the tooltip compatible with normal items (for checking 6-link drops), and it must have bricked magic items.

Thanks for reporting, I'll fix it for the next release.

**Comment by Lailloken** [comment]
I changed how the script detects a given item-base in v1.30.0, which should fix this issue.
