### ISSUE TITLE
Sanctum room recognition fails when the room is too high on the chart

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#196]
When a room in the sanctum chart is too high on the screen and the pop-up is too tall (so it moves to the side instead of right above), image recognition fails to identify it. Nothing happens when I try, even after I manually cap and name the room.
![изображение](https://user-images.githubusercontent.com/6707627/224959671-b17881aa-dd46-41f4-9f6f-766b333157f1.png)
I'm reporting this just for info, because it doesn't seem solvable - window position is dependent on what text it contains, and entirely unpredictable.

**Comment by Lailloken** [comment]
Thanks for reporting. Do you encounter this regularly? The script only reads the screen in a specified area around the cursor. This is to improve recognition speed and responsiveness. It's about 1/8 of the client-width to the left and right of the cursor and 1/4 of its height above the cursor. I have never seen a tooltip be offset by this much.

I'll take this behavior into consideration for future implementations, and maybe I'll do some testing with the current sanctum feature. Unfortunately, I'm busy right now trying to fix one of my SSDs that seems to have died, so I don't know when or if I get around to doing that testing.

**Comment by worldendDominator** [comment]
This is the only time I've seen this, but it should happen every time there's a room high up and with a long enough description.
The tooltip is offset to touch the room box on the side because it (barely) doesn't fit into available screen-space above. The same thing happens with items in inventory and stash and maps on the atlas screen too, so it's not something unique to the sanctum.

**Comment by worldendDominator** [comment]
By the way, trying to re-scan that tooltip breaks recognition for normal tooltips with that room name and I have to re-scan them afterwards.

**Comment by Lailloken** [comment]
> By the way, trying to re-scan that tooltip breaks recognition for normal tooltips with that room name and I have to re-scan them afterwards.

Hmm, yeah that's the game-client rendering UI-elements inconsistently depending on their position on screen. I usually counter-act that by making screen-reading less strict, i.e. allowing for greater discrepancy between calibrated screen-check images with what's on screen. Sanctum's screen-reading is already less strict than others but apparently not enough.

**Comment by PhantomGamers** [comment]
Any chance for sanctum support to be readded now that it's in the game again?

Not a big deal either way, I'm not a huge fan of the mechanic, but this info would make it way more enjoyable.

Thanks for your work :)

**Comment by Lailloken** [comment]
@PhantomGamers I have since added the cheat-sheet toolkit feature which has similar functionality but is universal (can be used for any mechanic). It has several types of overlays, and you can create tooltips similar to the ones in the old Sanctum feature: [wiki](https://github.com/Lailloken/Lailloken-UI/wiki/Cheat-sheet-Overlay-Toolkit)
