### ISSUE TITLE
Constant scanning causing lag

### ISSUE THREAD

**Issue by ReinhardtGore** [Lailloken/Lailloken-UI#20]
Is it possible to perhaps be able to assign a hotkey to show the interface instead of it constantly scanning to see if you have opened the tab which I assume it is doing? I am getting horrible frame skips when I have it running sadly. Otherwise this tool is amazing!

**Comment by Lailloken** [comment]
I didn't think this pixel check could cause performance issues since it only checks the color of a single pixel, and you are the first to raise this. I think I'll make the polling rate user-configurable (the default is 5 times a second) as a first step in trying to mitigate this issue. Thanks for your feedback.

**Comment by ReinhardtGore** [comment]
I made a quick example if that would help. I have tried downscaling to 1080p to test if it helped as well with no luck: https://youtu.be/3sM5s7x3K5o

**Comment by Lailloken** [comment]
Ok, that's extreme. Since you're online at the moment, we can actually test if decreasing the polling rate would help before I implement that. You can modify line 126 in the script (SetTimer, MainLoop, 200) and increase the number to, say, 1000 as a start. This would reduce the pixel check to once per second. If that doesn't do anything, the problem must be somewhere else.

**Comment by ReinhardtGore** [comment]
It still makes that noticeable blip/skip, but only once per second now, so at least we know it is that that is causing it 😁 I will be able to do more testing/digging around in the code as well after work if you'd like

**Comment by ReinhardtGore** [comment]
I just saw the edit, will check a little later only, can't at the moment

**Comment by ReinhardtGore** [comment]
> Ok, that's extreme. Since you're online at the moment, we can actually test if decreasing the polling rate would help before I implement that. You can modify line 126 in the script (SetTimer, MainLoop, 200) and increase the number to, say, 1000 as a start. This would reduce the pixel check to once per second. If that doesn't do anything, the problem must be somewhere else. EDIT: alternatively, change "RGB" to "Fast RGB" in lines 1252 and 1254.

Sadly no luck with these changes. the frame skip seems to align with the scan time for sure

**Comment by Lailloken** [comment]
Could you check which AHK version you're running?

**Comment by ReinhardtGore** [comment]
I have 1.1.33.02 installed

**Comment by Lailloken** [comment]
Alright, as a last resort, could you update your AHK? I'm trying to pinpoint where this anomaly is coming from in case this happens in the future.

**Comment by Lailloken** [comment]
Yes, I was thinking the same. I would just re-route the trigger from the pixel check to a hotkey. Or better, make the hotkey trigger the pixel check and either forward the keypress to the client and trigger the overlay, or only trigger the overlay. This way, the inventory and overlay don't 'flip-flop' around and miss each other.

**Comment by ReinhardtGore** [comment]
Good thinking, sounds like it would work a charm!

**Comment by Lailloken** [comment]
I had another idea, but I need your input. Is the lag so bad that interacting with the statue is unbearable? If not, I would make the hotkey resume the automatic pixel check, then stop it once it returned negative, i.e. once the inventory is closed. This way, you would be able to hide the overlay with ESC and by moving away from the statue. And it would also automatically hide when starting the encounter (which it wouldn't with the hotkey-solution).

**Comment by ReinhardtGore** [comment]
Interacting with the statue seems fine, it's just when moving/casting that you feel something is wrong. I think that is a good solution

**Comment by Lailloken** [comment]
OK, my solution is ready. I'm finishing some other stuff and will then release the new version. This fix will be undocumented in the release notes, but I will add it later to known issues in the readme. From next release onwards, there will be an additional Fallback.ahk file that has to be modified (instructions are inside), and you'll have to set a "fallback=1" flag in the config.ini. The archnemesis key will then behave as discussed, but you can only close the archnemesis inventory with ESC (or by any action if its the statue window). Please try it and give me your feedback.

**Comment by ReinhardtGore** [comment]
Awesome, just gave it a shot, and seems to be working as expected. When the inventory is open, the lag is present, but we expected that and it is not an issue. Outside of the window it is working perfectly! Thanks, amazing quick work 😁
