### ISSUE TITLE
Omni key just flashes the screen, does nothing.

### ISSUE THREAD

**Issue by JustinmClapperton** [Lailloken/Lailloken-UI#207]
What ive tried:
- followed guide and setup screens
![image](https://user-images.githubusercontent.com/5769149/229880793-02c6ad80-72e9-486e-a620-dfd5c4f59ece.png)
- alt and c are bound as normal
- tried different keys for omni key
- Tried opening when the context is correct
![image](https://user-images.githubusercontent.com/5769149/229880941-ceb936b8-00bc-4c07-aa60-b17005559916.png)
- In windowed full screen with a standard resolution  1440p

Happy to try other things.

Appreciate any help this overlay looks amazing and would love to start fully using it.

**Comment by Lailloken** [comment]
What are you trying to trigger when it flashes?
Does the context-menu open when you omni-click an item?

**Comment by JustinmClapperton** [comment]
I was trying the above for buying gems, Ive tried it on the betrayal screen and I just did your test on an item.  The whole screen just flashes then nothing happens.  Let me know if there is anything else I can share to help.

**Comment by Lailloken** [comment]
Could you right-click the icon in the system-tray and click help to see which version of AutoHotkey you're running?

**Comment by JustinmClapperton** [comment]
![image](https://user-images.githubusercontent.com/5769149/229883886-c1e9ebd6-3ce8-4ceb-a7c2-d63e2bb34e26.png)

**Comment by Lailloken** [comment]
If you have Discord, you can add me: Lailloken#6816
If not, copy something into the clipboard, then omni-click an item and check in notepad or something if the item's information has been copied into the clipboard. Other than that, maybe try updating AutoHotkey. If the context-menu on items doesn't even work, there seems to be a deeper problem.

**Comment by JustinmClapperton** [comment]
Added you

**Comment by JustinmClapperton** [comment]
Resolved thanks. 

For any others that see this, I updaed to the most recent 1.1.36 AHK and reset all my Omni keys in the Omni keys section
