### ISSUE TITLE
Feature request - Map-list when browsing for maps

### ISSUE THREAD

**Issue by Nitrak** [Lailloken/Lailloken-UI#21]
If a preferred recipe is set and there are missing components add a suggested list of maps to run based on the components missing.

I know it is possible to see a suggested list by hovering over the missing components, but when switching to map-tab this list disappears and it can be hard to remember 10+ maps.

So if possible have a way to keep the overlay open when searching for maps, either with some key-bind or detection of map-tab UI.

Thanks for a nice tool!

**Comment by Lailloken** [comment]
Yeah, I ran into the limit as well. I have an idea: when you open the list by shift-clicking, the panel opens as a movable window, and you can click the map names for filtering in the map tab.

**Comment by Nitrak** [comment]
That would be awesome.

Thanks again for this script! :)
