### ISSUE TITLE
timeless search since tree is changed

### ISSUE THREAD

**Issue by NomaratheF** [Lailloken/Lailloken-UI#210]
will you updete timeless search since tree was updated?

**Comment by NomaratheF** [comment]
also this 
![image](https://user-images.githubusercontent.com/122170801/229951404-144c33ed-4823-4f37-9351-d3256ab499c1.png)

**Comment by NomaratheF** [comment]
> also this ![image](https://user-images.githubusercontent.com/122170801/229951404-144c33ed-4823-4f37-9351-d3256ab499c1.png)

solved. do you have ahk requirements? if so its not obvious, that you need 1.1.36 version but not 2.0

**Comment by Lailloken** [comment]
> will you updete timeless search since tree was updated?

I'll update it before launch. I can't update it like the websites or PoB because it uses in-game highlighting, and that wouldn't work if the new tree is not in the game yet.


> do you have ahk requirements? if so its not obvious, that you need 1.1.36 version but not 2.0

I was made aware just yesterday that 2.0 is not beta anymore. I'll update the readme, thanks.

**Comment by NomaratheF** [comment]
> 

thanks a lot
