### ISSUE TITLE
Script crashed with leveling tracker on at Siosa vendor (library)

### ISSUE THREAD

**Issue by Luphana** [Lailloken/Lailloken-UI#212]
Script crashed with leveling tracker on while buying gems from Siosa.
Multiple Gems from multiple tabs.
Fire Trap - Trap Damage - Armageddon - Ele Focus

I've bought two gems and suddenly the script crashed.
When i tried to replicate the same thing (buy few gems from siosa while on the level tracking step) it crashed again but without any error messages.

**Comment by Lailloken** [comment]
Could you right-click the L-icon in the system tray, click "help", and tell me which version of AutoHotkey it's displaying?

**Comment by Lailloken** [comment]
Found the issue. Should be fixed in v1.30.3-hotfix1

**Comment by Luphana** [comment]
It's fixed thank you :)
