### ISSUE TITLE
Leveling Tracker: Gems only

### ISSUE THREAD

**Issue by SeeTwoDev** [Lailloken/Lailloken-UI#213]
Is there a way to import a gems only Exile Leveling route that i'm not seeing?

**Comment by Lailloken** [comment]
No, it's not supported. The gems only mode culls everything except buying the gems, i.e. the export doesn't include any location references that my script could use to determine where the player is at the moment (via cross-checking with the client.txt log-file).
The guide-overlay wouldn't know when to display the gem prompts or when to switch to the next one, etc. So in its current form the "gems only" export is unusable in LLK-UI.

**Comment by SeeTwoDev** [comment]
Thanks for the quick answer
