### ISSUE TITLE
Buy gems (Highlight via Omni Key) closes vendor window, opens chatbox

### ISSUE THREAD

**Issue by str0yd** [Lailloken/Lailloken-UI#215]
1. Opened vendor window
2. Pressed and hold F5 (my configured Omni Key)
3. Vendor window closes
4. Chat box opens
5. Reopening vendor window and holding Omni Key again does paste the search string

Closing the chat box --> jump back to 1. opens the chat box again, does not paste the search string

https://user-images.githubusercontent.com/29361982/230596196-c09dff66-246d-40ae-bd4a-9399d660270a.mp4

**Comment by Lailloken** [comment]
Does it also happen with a different F-key? I'm trying to replicate this, but it's not happening on my end.
Are you running other tools as well? Some have "/hideout" macros bound to F5.

**Comment by str0yd** [comment]
Same with default (middle mouse button) or CTRL+F. I just closed anything else running in the background, but it still happens.
Running steam version of POE...

**Comment by str0yd** [comment]
Also, it only works on the first side of the vendor shop. When the chat box is open and I go to the 2nd side (to the gem list) it just closes the vendor box and the chat.

**Comment by Lailloken** [comment]
Do you have search-strings set up for a vendor?

**Comment by str0yd** [comment]
No, I disabled the checkboxes, still the same issue.

**Comment by Lailloken** [comment]
The clip shows a 5 in chat right before the regex-string. Do you know why it's there?

**Comment by str0yd** [comment]
Yeah I think i hit the ^ button before. On German keyboard layout it does not type the ^ character immaterially but waits for the next input, it's kinda weird. I do not think that this is related to the behaviour because it never happened again.

**Comment by Lailloken** [comment]
What you could try: keep the omni-key on F5 and bind the secondary omni-key (items) to any other key. After restarting, pressing F5 should activate the gem-strings without any prior input. We need to find out what's causing the window to close -- there has to be some input from somewhere.

**Comment by str0yd** [comment]
Now it works properly pressing the omni-key only with open vendor window.

However:
Pressing and holding down the omni-key item just in town now opens the inventory.
Pressing and holding down the omni-key item again with open inventory closes the inventory and opens the chat
Pressing and holding down the omni-key item again with open chat posts the string shown in the video or here: ![image](https://user-images.githubusercontent.com/29361982/230611134-15f66fd4-7c45-4311-850c-d0d7c272b808.png).

**Comment by Lailloken** [comment]
What's your in-game keybind for inventory?

**Comment by str0yd** [comment]
My keybind for inventory is C.

**Comment by Lailloken** [comment]
![image](https://user-images.githubusercontent.com/61888437/230615077-a63f2ae2-bd28-40d0-ae20-8e5cb40e8d03.png)

You must have missed this :D
You'll have to use the two separate omni-keys from now on. The secondary one for features related to items, the regular one for everything else. The issues you're having are due to the fact that the game triggers whatever is bound to C (unless it's the character-sheet) whenever you copy something into clipboard without actually hovering an item. It's a weird bug that makes trouble-shooting REALLY hard because rebinding C is not very common.

**Comment by str0yd** [comment]
Oh mah :D thank you very much. Of course I skipped the setup stuff xD
