### ISSUE TITLE
The script needs to convert some setting - error message

### ISSUE THREAD

**Issue by HobbitM** [Lailloken/Lailloken-UI#216]
I get the error message when running the script for the first time like in title. To be exact :
The script needs to convert some settings for an updated feature but it couldnt correctly read yout client-resolution. It will now restart.

**Comment by HobbitM** [comment]
Ok i think my resolution is not supported, nvm. well thats sucks but what you gonna do .. cheers

**Comment by Lailloken** [comment]
You can re-download it via the front-pages download button. There is a way to run the client with a custom resolution to make it work. There was just a bug that wouldn't let you get to the settings.
