### ISSUE TITLE
Custom font error

### ISSUE THREAD

**Issue by Haroldyolo** [Lailloken/Lailloken-UI#217]
Hi,

Trying to setup this before the league start as recommended by ZiggyD, but getting

22. include file "data\class_customfont.ahk" cannot be opened

Any idea how to fix it?

Thanks for the amazing tool!

**Comment by Lailloken** [comment]
Assuming everything was extracted correctly, it's probably an AutoHotkey issue (outdated install or something). If you're using some sort of launcher or command-line to launch it, you have to specify the working directory as well.

**Comment by Haroldyolo** [comment]
I found the powershell solution in here and that worked, however simply right clicking and starting the script does not, even as an admin

**Comment by Aeyzeins** [comment]
> Assuming everything was extracted correctly, it's probably an AutoHotkey issue (outdated install or something). If you're using some sort of launcher or command-line to launch it, you have to specify the working directory as well.

Having the same problem here as well, Im using the latest version of AHK v1.1 and still not able to run it

**Comment by Lailloken** [comment]
@Aeyzeins Did you just update? Someone mentioned in another thread how an update didn't fix it but a reboot after that did.

**Comment by Desomph** [comment]
@Aeyzeins @Haroldyolo  Did you, by any chance, forget to extract the folder and instead you ran the UI script from the zip? Because that happened to some people.

**Comment by Haroldyolo** [comment]
> @Aeyzeins @Haroldyolo Did you, by any chance, forget to extract the folder and instead you ran the UI script from the zip? Because that happened to some people.

Nah, mine is fully extracted

**Comment by FDuhen** [comment]
Running the script as adminsitrator may help you fix this problem

**Comment by jax999** [comment]
I prob didnt read manual correctly but when i got the same error i just moved the folder to the game folder of the game to resolve the issue.
in my case since i use steam it is "C:\Program Files (x86)\Steam\steamapps\common\Path of Exile\Lailloken-UI-main"

Also i run the script after starting the game obviously.

**Comment by Aervanath** [comment]
I had the same issue as OP. With my other AHK scripts, I can simply right click the AHK button on my taskbar and click the script name. Trying that with this script gives you an error.
Two solutions that worked for me:
1) Create shortcut and put it on the desktop
2) compile the script into an application and then run that instead

**Comment by ahakkar** [comment]
None of it helped. Extracted to own folder on win11, no. Run from commandline, no. Run with shortcut - no. Run with compiled .exe, no. Using Autohotkey 2.0.2 so it should be new enough.

**Comment by Lailloken** [comment]
@ahakkar it doesn't work on 2.x, you need 1.1.x

**Comment by ahakkar** [comment]
Ok. I had maybe 1.1.26 but it did not work. I tried 2.0.2 but it did not work. Now I installed 1.1.36.02 and it works. So at least on my computer it seems to require a quite specific version of AHK, not just 1.1.x.

**Comment by LordOnrah** [comment]
Had the same error as OP. Shortcut on desktop fixed that one but I'm now stuck on Error at line 1022.  #include file "modules\alarm-timer.ahk" cannot be opened.

**Comment by Lailloken** [comment]
@Haroldyolo I've added two potential fixes for this issue. It's not a new release but it can be downloaded via the download button on the front-page. Could you please report back:
1) whether simply launching Lailloken UI.ahk works correctly now
2) alternatively, whether launching it via the Launcher.ahk works or not

**Comment by Haroldyolo** [comment]
> @Haroldyolo I've added two potential fixes for this issue. It's not a new release but it can be downloaded via the download button on the front-page. Could you please report back:
> 
>     1. whether simply launching Lailloken UI.ahk works correctly now
> 
>     2. alternatively, whether launching it via the Launcher.ahk works or not

@Lailloken I can confirm both are now working from the new release, thank you for the quick fix and the amazing tool!
