### ISSUE TITLE
Problem with windowed game and window moved from initial launch position

### ISSUE THREAD

**Issue by Furiouss38** [Lailloken/Lailloken-UI#219]
Hi,
First of all good job with thoses tools even if for now I'm just able to see in video how others are able to use them.
I have a rather specific issue with how I use the POE Client on my screen. I have an ultrawide 49" 3840*1080 monitor.
So I use POE on half my screen in windowed mode, but POE doesn't remember how I put the window and always start in the middle of the screen : 
![before moving window](https://user-images.githubusercontent.com/16611057/230640575-b72d4ed6-b63c-4deb-adf5-f60623881d6c.png)
so I use windows key+left arrow to put my POE window in full height available (with the windows bar active) and taking half the width of the screen like this : 
![after moving window](https://user-images.githubusercontent.com/16611057/230640581-db3aa346-57d7-4ba2-9a45-6d56f0653f00.png)
the issue is with my POE Window moved and resized from it's starting position, your tool can only be used on a little bit less than half my game since it thinks it's still in the starting position :(
I know my use case is specific, maybe i'm the only one playing like that but I wanted  to say it anyway, just in case i'd be able to use the tool some day.

**Comment by Lailloken** [comment]
You can right-click the LLK-UI panel or type r.llk into chat to restart it. As long as the window has a supported vertical resolution after the restart, the script should pick up the new position. Maybe run a custom resolution that works, drag the window instead of pushing it with win+arrow, and then restart it.

**Comment by Furiouss38** [comment]
due to windows bar, my resolution  is : 1920*1008
If I use custom resolution, and set for exemple 1920*900 and loose 108px of screen if I move my window with dragging it by the title bar, your tools are still confined in the 1980*900 in the center of the screen, as show on the screenshot, the book and llk menu can't go farther on the left and leveling guide is not entirely over POE
![test](https://user-images.githubusercontent.com/16611057/230646170-4ea1179d-8e03-4583-b3ff-85541aa7a284.png)

**Comment by Lailloken** [comment]
![image](https://user-images.githubusercontent.com/61888437/230647315-54356ce9-f61b-461e-8bf7-9d4cbf9ba7ee.png)

Here's 1920x900 on a 1440p monitor. Make sure to not check "apply on startup" for the custom resolution, then right-click the LLK-UI panel.

**Comment by Furiouss38** [comment]
I don't understand, I tried multiple times before writing my last  comment and it kept being stuck in the middle of the screen.
I tried again after your comment and now it works -_-'
Good for me but I don't understand why :D
I can even resize my window so I don't loose 108px of POE's height (I just can't use the overlay in those 1920x108px but who cares)
Thanks for your help.

**Comment by Lailloken** [comment]
You have to be careful. If you're unlucky some screen-checks won't work because the game renders UI elements inconsistently (pixelated, i.e. they don't look the same when you open them at different points in time). The script may fail to recognize the UI that's currently open in game, and the feature you want to access may not activate.
