### ISSUE TITLE
Feature Request - Option to add components to burn list if more than X is available.

### ISSUE THREAD

**Issue by Nitrak** [Lailloken/Lailloken-UI#22]
My friend asked me to put up this issue:

Is it possible to make it an option that you can set for a number of components so that when you own more than X of a certain type then it gets added to the "Available to burn" list.

For example, if I have the limit set to 3 and I have 3 Hasted then Hasted gets added to the burn list

**Comment by Lailloken** [comment]
So as a general option, regardless of it being in prio or non-prio? I'll think about it. What matters most is how I can add something like this into the UI -- I generally don't want a dedicated options window. Maybe as an 'advanced option' via the config.ini.

**Comment by Nitrak** [comment]
Advanced option in the config.ini works just fine. Most people can open a text file :D

**Comment by scrangos** [comment]
I'd like this as well, or an inventory list so i can see which components im overflowing with and should just spend them

**Comment by Lailloken** [comment]
> I'd like this as well, or an inventory list so i can see which components im overflowing with and should just spend them

You can hold-click the PRIO-label to see the surplus of mods connected to the prio-list, and the other stuff should appear in the burn lists. If that's not what you meant, let me know.

**Comment by scrangos** [comment]
> > I'd like this as well, or an inventory list so i can see which components im overflowing with and should just spend them
> 
> You can hold-click the PRIO-label to see the surplus of mods connected to the prio-list, and the other stuff should appear in the burn lists. If that's not what you meant, let me know.

I meant single components that are not associated with the priority list.  On the burn list im getting assembled tier 2-3 mods that while not on the priority list I don't want to use yet.  while having like 5-6 copies of a base mods not on the priority list.  Perhaps i shouldnt even pick them up but they're still useful as a 4th component while building up 3 mod recipes.

**Comment by Lailloken** [comment]
> I meant single components that are not associated with the priority list. On the burn list im getting assembled tier 2-3 mods that while not on the priority list I don't want to use yet. while having like 5-6 copies of a base mods not on the priority list. Perhaps i shouldnt even pick them up but they're still useful as a 4th component while building up 3 mod recipes.

I see. Yeah, I limited the burn list to seven entries to keep the panel from taking too much height. I have to make sure the UI fits on all resolutions. I could make the length of the list user-configurable via the config.ini in a future update.

**Comment by Biggoron144** [comment]
Seconding this idea, it'd be a nice addition.

**Comment by scrangos** [comment]
> > I meant single components that are not associated with the priority list. On the burn list im getting assembled tier 2-3 mods that while not on the priority list I don't want to use yet. while having like 5-6 copies of a base mods not on the priority list. Perhaps i shouldnt even pick them up but they're still useful as a 4th component while building up 3 mod recipes.
> 
> I see. Yeah, I limited the burn list to seven entries to keep the panel from taking too much height. I have to make sure the UI fits on all resolutions. I could make the length of the list user-configurable via the config.ini in a future update.

That window is still missing the amounts for each component available to burn though.

**Comment by scrangos** [comment]
well, i have the patience of a caffeinated fruit fly on crack so i went and did it on my end https://i.imgur.com/c2LAMUe.png. heres the code if you want to diff it or something.  https://pastebin.com/8MUjdSrp

**Comment by Lailloken** [comment]
> That window is still missing the amounts for each component available to burn though.

You didn't mention that specifically. I didn't account for people hoarding non-prio assembled mods when I planned the system :D.

> well, i have the patience of a caffeinated fruit fly on crack so i went and did it on my end

Even infinite patience wouldn't have sufficed. I didn't know you wanted that because you didn't specify. I like the comparison, though :D.

**Comment by Lailloken** [comment]
The next update will implement the requested behavior a little bit differently: You will be able to set a threshold above which prio-surplus will be burned, and the burn list will include quantities (as [scrangos](https://github.com/scrangos) did for himself), so there you can decide for yourself when to burn stuff.
