### ISSUE TITLE
Cant get script to run

### ISSUE THREAD

**Issue by ThoronElee** [Lailloken/Lailloken-UI#227]
These are the errors i received when trying to run the script. I dont know what i am doing wrong but i can not get it to start running. I tried with both 2.0 and 1.1 AHK

![image](https://user-images.githubusercontent.com/130197213/230699032-bb982dd6-41bb-42e9-9351-8d3e0fb31d57.png)
![image](https://user-images.githubusercontent.com/130197213/230699038-b1373734-e84b-4764-9ac1-78c445a79fee.png)
![image](https://user-images.githubusercontent.com/130197213/230699051-a72aca10-439f-4c6b-9876-89b0292a2315.png)

**Comment by Lailloken** [comment]
The Switch A_ThisHotkey error is related to AutoHotkey being outdated.
The second one is kind of tricky. Some people also fixed it by updating/reinstalling AHK, for some it was fixed after updating/reinstalling and rebooting afterwards. One person told me that creating a shortcut of the script and putting it on the Desktop fixes it.

**Comment by Peanutte** [comment]
> 

second error fix to make shortcut worked for me
