### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by PJacek** [Lailloken/Lailloken-UI#23]
When clicking on a recipe in the ready/burn recipe window it blinks and does nothing. Everything else seems to work. I can scan and track recipes and I have no problems with click hold.
AutoHotkey 1.1.33.10, script version 1.20.2
I also use Awakened PoE Trade but no other overlays

**Comment by Lailloken** [comment]
Does this happen every time you click something, and for both recipes and single mods? There were a few people in beta who occasionally had this problem, but never enough to really find the source of the issue. I'll see if I can find something in the code. Could you try disabling as many background applications as possible (such as mouse/keyboard software) and see if something changes?

**Comment by PJacek** [comment]
Yes, it happens for both recipes and single mods. I disabled Awakened PoE Trade and Logitech Gaming Software, no change. Copying to the clipboard seems to work. I can paste both in game and here `^(lunaris-|solaris-|mirror.i|mana.sip)`. I also tried first clicking the search box to activate it but that doesn't seem to help

**Comment by Lailloken** [comment]
Okay, something else. Can you type something into the archnemesis search field, hit enter, then press scan. Everytime scan is pressed the search field should get cleared beforehand. I want to see if that behaves normally.

**Comment by PJacek** [comment]
Doesn't work, the input isn't cleared and the scan fails to recognize mods.

**Comment by Lailloken** [comment]
Alright. Press enter to open the chat, and while it's open click a recipe/mod in the ready lists.

**Comment by PJacek** [comment]
Nothing gets pasted into the chat window

**Comment by Lailloken** [comment]
Okay, I thought maybe ctrl doesn't get send to the client, but it seems none of the keys get send. Unfortunately, it's getting late over here, so I'll have to look into it tomorrow. Thanks for helping me this far.

**Comment by Lailloken** [comment]
Could you edit the script in line 3 by replacing "#KeyHistory 0" with "#InstallKeybdHook"? Save the changes and run the script again.

**Comment by PJacek** [comment]
No difference

**Comment by Lailloken** [comment]
Okay, I'm running out of ideas. Googling around, I found some info that running autohotkey as admin might help with sending keypresses. Maybe try that.

**Comment by PJacek** [comment]
Running as admin works. It's probably because I'm running PoE as admin. I don't remember why I configured it like that. I was probably trying to solve some bug or performance issues.

**Comment by Lailloken** [comment]
Glad it works now. Have fun!
