### ISSUE TITLE
Unhide setting tab thingy top left corner?

### ISSUE THREAD

**Issue by KongGal** [Lailloken/Lailloken-UI#232]
So i wanted to create a frame for minions but the little top left panel was in the way so i hid it... and by mistake pressed tab and there was a new version. now the tab is gone and i can't figure out how to get it back

**Comment by Lailloken** [comment]
You can type .llk into chat to open the settings menu. You can also move the panel anywhere you want by dragging it. Personally, I put it here:
![image](https://user-images.githubusercontent.com/61888437/230730826-eafef8be-3a69-4191-82f6-a4c8651c7963.png)
