### ISSUE TITLE
item-info doesn't seem to work

### ISSUE THREAD

**Issue by moffitj** [Lailloken/Lailloken-UI#234]
Just updated to the latest main.

I middleclick an item and the item context menu opens, but that's it. The documentation suggests that instead an item-info popup should show.

I set up the screenchecks and they tested positive.

**Comment by Lailloken** [comment]
The item-info is activated by a long omni-click on an item. Once it's open, a normal omni-click on subsequent items will activate it.

**Comment by moffitj** [comment]
How long of a click? I held for 10 seconds and did not get it.

I hover over an item in my inventory and it displays the in-game tooltip. I press and hold the omni button and the in-game tooltip disappears and the item context menu appears. No amount of holding seems to make the item-info popup appear.

I also enabled the shift-clicking option to see if it would show when identifying items and that path didn't work either.

I also run awakened POE trade so maybe that is interfering. Will try later.

**Comment by Lailloken** [comment]
It's 200ms. There must be an issue that causes the script to not detect the key as being held down. You can try long omni-presses on maps to see if it shows the horizon tooltip. Alternatively, you can go to the settings menu, omni-key section, click into the hotkey field and press whichever key it is bound at the moment. The text next to it should turn green. If it doesn't stay green for the duration of the key-press, then that suspicion would be confirmed.
![image](https://user-images.githubusercontent.com/61888437/230760522-36b80070-b4d3-40b1-90bd-a23267f884e8.png)

**Comment by SataD1sc** [comment]
I have a problem too. When i try to use it on item it just shows 1 bar like this.
![image](https://user-images.githubusercontent.com/39724443/230783970-367e2625-1996-48c3-9c80-55c50cc47478.png)
