### ISSUE TITLE
2 Feature requests: Map pathing images (ala qik), XP/Overlevel tracker

### ISSUE THREAD

**Issue by sclient** [Lailloken/Lailloken-UI#237]
Poking around today and found this tool had recently released an update, but unfortunately the method by which it expects you to manually edit in a build is super archaic. OTOH, it has these nifty images (that I find a bit more intuitive than the occasional text descriptions Lai offers), and would like to request a 'graphic pathing' option for your tool.

Also found the XP/overlevel tracker to be kind of useful, as Im always manually attempting to keep an eye on that, and it seems like a perfect thing to implement here (again that dated tool expects you to manually enter offsets to place each element instead of just dragging as you would in the 21st century, lol).

Thanks for your tool! Have been occasionally following your every addition on the reddit, and finally ZD got me invested into actually installing it for crucible, and it is fantastic!

(https://github.com/JusKillmeQik/PoE-Leveling-Guide)

**Comment by Lailloken** [comment]
> (that I find a bit more intuitive than the occasional text descriptions Lai offers), and would like to request a 'graphic pathing' option for your tool.

The guide-text is based on exile-leveling, with occasional re-arrangement from my side to better fit the panel.
I'll have to verify if the available layouts are still up to date. I think I read somewhere that GGG changed seeding a while back, but I'm not sure. I'm also unsure about how to implement these graphics, I personally don't like how cluttered the screen looks at times in qik.

> Also found the XP/overlevel tracker to be kind of useful, as Im always manually attempting to keep an eye on that, and it seems like a perfect thing to implement here

Certainly easy enough to implement. I'll think about it.

**Comment by sclient** [comment]
The qik thingy sets it up with a timer you can set to autohide it after some configured amount of time which is helpful. It lets you move them, but its the clunky offset number method again, so feels bad. 

There are some maps that alter the layouts (mostly later when betrayers and such start popping in), but generally it is pretty quick to tell if a direction you are headed in seems to match one of the images or not, and I have to mention I just got to the brine king faster than I ever have minutes ago with one, haha. 

Im definitely sold at this point, so ill use it either way (I think itd take anyone a single league start to believe, haha), just always nice if it makes sense to get less tools total, especially since your implementation is just so modern by comparison. :)

**Comment by Lailloken** [comment]
This is what I'm testing right now for v1.50 (which should hopefully be ready for next league): I have added two small panels that show how many zone-layout img-files are available for the current area (bottom-left, ZL) and how much exp you're getting.

As I mentioned before, I don't like having them pop up or be on screen automatically with every transition, so they will be on the left edge of the screen while holding down TAB (configurable) instead. Scrolling will zoom in/out.

Let me know what you think, and feel free to suggest improvements.

![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/87595326-a7b9-4e63-98bc-9062ffcfa0d0) 
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/b49212f7-d6ed-47d3-9cae-06ac775cbee7)
