### ISSUE TITLE
Heist Marker Issues with Map Tracker

### ISSUE THREAD

**Issue by Eigengrau16161D** [Lailloken/Lailloken-UI#240]
Just started using this after coming back to Poe, I have to say this is one of the neatest frills-free utility apps I've run and I really appreciate you sharing your wonderful work here. 
I've noticed an odd quirk with the Map Tracker. When logging Heist markers, the text and the quantity seems to be enough to roll over into a new line, which then causes error messages and refuses to log the map until I right click the 00) off the list. I've only noticed this happening with Rogue markers so far, but it's consistent for any large number of Heist Markers
![image](https://user-images.githubusercontent.com/55037374/231274294-cb9f5e1f-e0ee-4e99-b09d-a8c2737a02e4.png)
![image](https://user-images.githubusercontent.com/55037374/231274408-41b0cb01-bcae-4aca-a1fc-59633b7e735b.png)

**Comment by Eigengrau16161D** [comment]
Update from breaking up the stack and seeing what the break point is, it's once you hit 4 digits.

**Comment by Lailloken** [comment]
Could you ctrl-c a 4-digit stack and paste it here? It's probably an oversight on my end with the thousands separator (1,000 vs 1.000)

**Comment by Lailloken** [comment]
Never mind, I was able to verify it on my end. You can use this hotfixed build for now: https://github.com/Lailloken/Lailloken-UI/archive/refs/heads/dev.zip

**Comment by Eigengrau16161D** [comment]
Amazingly fast response, wow! 
The hotfixed build didn't work, but I've got new error logs 
![image](https://user-images.githubusercontent.com/55037374/231569165-4c7a2764-1f9d-4f1f-acad-c356b4ae697d.png)

> Here's the 3, 4, and 5 digit stack
> Item Class: Stackable Currency
> Rarity: Currency
> Rogue's Marker
> --------
> Stack Size: 100/50,000
> --------
> Creates a portal to the Rogue Harbour from a Town or Hideout
> Used as Currency for services in the Rogue Harbour
> --------
> Right click on this item while in a Town or Hideout to use it.
> Shift click to unstack.
> ```
> 

> 
> Item Class: Stackable Currency
> Rarity: Currency
> Rogue's Marker
> --------
> Stack Size: 1,000/50,000
> --------
> Creates a portal to the Rogue Harbour from a Town or Hideout
> Used as Currency for services in the Rogue Harbour
> --------
> Right click on this item while in a Town or Hideout to use it.
> Shift click to unstack.

> Item Class: Stackable Currency
> Rarity: Currency
> Rogue's Marker
> --------
> Stack Size: 10,000/50,000
> --------
> Creates a portal to the Rogue Harbour from a Town or Hideout
> Used as Currency for services in the Rogue Harbour
> --------
> Right click on this item while in a Town or Hideout to use it.
> Shift click to unstack.
> 

```

**Comment by Lailloken** [comment]
omg, I shouldn't code right before going to bed. You can re-download the dev build, and it should now work correctly.

**Comment by Eigengrau16161D** [comment]
Can confirm that this new update has fixed the bug. Thank you very much!
