### ISSUE TITLE
Unable to calibrate Betrayal

### ISSUE THREAD

**Issue by Voltstriker** [Lailloken/Lailloken-UI#243]
Looking to set up image recognition for the betrayal info - have successfully calibrated the UI by taking the screenshot of the background to the lower left, just above the healthbar.

I'm looking to now take screenshots of the individual character portraits as per the instructions to set up image recognition, but when pressing middle mouse button and right click (in either order of execution), the snipping tool doesn't show up.

I am running the game in windowed fullscreen at 1440p - other image recognition works fine in terms of taking screenshots and its reading of my monitor.

**Comment by Eigengrau16161D** [comment]
Just to confirm, Betrayal Info has two different setups, one using image recognition, and one just using the table. Both need the UI to be calibrated, but the character screenshot tool won't show up in the basic mode. Have you toggled "use image recognition" in the betrayal settings?

**Comment by Lailloken** [comment]
> successfully calibrated the UI by taking the screenshot of the background to the lower left, just above the healthbar.

You were probably using an old YouTube video as a guide. I had to change the location of the screen-check because the bottom-left of the syndicate board caused issues in some situations when there was a high concentration of members in fortification and transportation. This led to text boxes appearing right above the healthbar, making the screen-check return negative.

Always use the help-tooltips in the current version of the script, as they are up to date.

![image](https://user-images.githubusercontent.com/61888437/231946070-d42484e4-20e8-4c25-8aea-80a73933edb1.png)

**Comment by Voltstriker** [comment]
> > successfully calibrated the UI by taking the screenshot of the background to the lower left, just above the healthbar.
> 
> You were probably using an old YouTube video as a guide. I had to change the location of the screen-check because the bottom-left of the syndicate board caused issues in some situations when there was a high concentration of members in fortification and transportation. This led to text boxes appearing right above the healthbar, making the screen-check return a negative result.
> 
> Always use the help-tooltips in the current version of the script, as they are up to date.
> 
> ![image](https://user-images.githubusercontent.com/61888437/231946070-d42484e4-20e8-4c25-8aea-80a73933edb1.png)
> 
> EDIT: the "test" button in the screen-checks menu probably returns a positive test nonetheless, which needs to be changed because it causes unnecessary confusion.

I was indeed using an old YouTube video - now that I have recalibrated, it is letting me do the individual portrait screenshots.

While it now makes sense, it wasn't immediately obvious that I could click on the "BETRAYAL" lettering and have it open a help menu. As a suggestion, it might be an idea to make the help buttons/links more consistent across the tool by adding the book icon next to the words "BETRAYAL" and "STASH" to help flag that you can click on them for help.

Thanks for your help.
