### ISSUE TITLE
CSV Delimiter error

### ISSUE THREAD

**Issue by daniel-lindem** [Lailloken/Lailloken-UI#244]
The map "Caer Blaidd, Wolfpack's Den" will cause an error when loading the CSV. Suggest wrapping map column in quotation marks. Alternatively use semicolon as delimiter, should be more robust.

Loaded into Excel
![image](https://user-images.githubusercontent.com/85883111/232171871-7e10cfe5-c73e-4965-bd17-21b95ac8223c.png)
Displayed in VSCode
![image](https://user-images.githubusercontent.com/85883111/232171838-152b5733-7ce8-47b7-9ee1-edb5e88eac54.png)

**Comment by Lailloken** [comment]
Ah, right. Thanks for reporting.
