### ISSUE TITLE
Setting up Betrayal

### ISSUE THREAD

**Issue by PirateWibber** [Lailloken/Lailloken-UI#246]
I'm trying to set up betrayal UI and I have gotten to the point where I have to make it recognize the different board members..
It says I have to right-click and omni-key, but every time I press the Omni-key it closes everything and opens my inventory

I tried going into input setup to see what was going on, and i noticed that when I launch your autohotkey script, instead of being bound as 'middle mouse' it is now instead bound as 'Control+C'.

Any solution? :S

**Comment by Lailloken** [comment]
Is your inventory bound to the c-key? If so, you have to go to the "hotkeys" section of the script's settings menu and read the help tooltips near the top.
You can reset the omni-key by clicking into the hotkey-field and pressing backspace or the DEL-key.

**Comment by PirateWibber** [comment]
I made it work, thank you :)..
Only thing i can't seem to get working yet though, is the pictures of the desired members over each "place".  will they come when i have all the names of all the different members or am I missing something ?

**Comment by Lailloken** [comment]
Do you mean this?
![img](https://user-images.githubusercontent.com/61888437/176613608-2c92cc69-4786-473a-9249-ed3ced39fe38.png)

These pictures will be placed wherever a member has teal highlighting:
![image](https://user-images.githubusercontent.com/61888437/233794526-f508b4cc-fd32-4a83-b28e-5bd0e9bca4ef.png)

Holding the omni-key while the syndicate board is open will show this prio-view
