### ISSUE TITLE
Something in  ini/screen checks causes item tooltip window to close immediately

### ISSUE THREAD

**Issue by jderagon** [Lailloken/Lailloken-UI#247]
[gamescreen]
color 1=0xB88E75
[inventory]
color 1=0x0D0B08
color 2=0x181614
color 3=0x050404
[skilltree]
last coordinates=1232,73,1334,108
[betrayal]
last coordinates=

Above is my ini/screen checks (1440p).ini file. 

I had been using everything just fine until one day the item tool tips were showing for a half second then closing immediately. I tried to copy a fresh version over top of my old directory but had the same issue. Starting with a fresh copy though and the issue was gone. 

I then dragged over my .ini files one at a time and reloaded trying to find which was causing it, and when I dragged this one over is when the issue started to occur again.

**Comment by jderagon** [comment]
Playing a bit more, removing the Inventory section is what seems to fix the issue.

**Comment by Lailloken** [comment]
It's probably the inventory colors being outdated because of a game-update. Recalibrating the inventory-check should fix it. The item-info tooltip and any markers will disappear if the script detects the inventory as closed. This is so everything disappears automatically after vendoring stuff (because the inventory will close with the vendor window).

**Comment by jderagon** [comment]
> It's probably the inventory colors being outdated because of a game-update. Recalibrating the inventory-check should fix it. The item-info tooltip and any markers will disappear if the script detects the inventory as closed. This is so everything disappears automatically after vendoring stuff (because the inventory will close with the vendor window).

Ok great, that is it exactly, thank you for the help!
