### ISSUE TITLE
Map-Info doesn't show [Monsters Cannot be Taunted / Action Speed Cannot be Modified]

### ISSUE THREAD

**Issue by Kidyeon** [Lailloken/Lailloken-UI#248]
I know this is a small feature, but since I'm someone who largely plays Blight, I was hoping to be able to tag this when using Map-Info
![image](https://user-images.githubusercontent.com/15699373/236231069-3d80677a-5d82-4e1c-b5bb-39e5afd861e2.png)

**Comment by Lailloken** [comment]
Yes, I noticed that as well. GGG swapped the two lines around, which makes the tooltip miss the mod. I fixed it in a preliminary version I haven't officially released yet (I suddenly lost interest in the league and haven't fully tested all the changed I made).

You can edit the file "map mods.ini" in the "data" folder. Search for the line
`[monsters' action speed cannot be modified to below base value|monsters cannot be taunted]`
and replace it with
`[monsters cannot be taunted|monsters' action speed cannot be modified to below base value]`

**Comment by Kidyeon** [comment]
Gotcha, thanks! Worked like a charm. 
Thanks for the quick response despite your loss of interest too
