### ISSUE TITLE
[Suggestion] Leveling Guide Enhancements

### ISSUE THREAD

**Issue by darkscion0** [Lailloken/Lailloken-UI#249]
Not sure if it's possible but it would be nice to have "per character" leveling guides + progress. 

Would also be nice to have a hotkey to show/hide the leveling guide.

**Comment by Lailloken** [comment]
> Not sure if it's possible but it would be nice to have "per character" leveling guides + progress.

Off the top of my head, this sounds like a lot of work for such a niche use-case.
<br>

> Would also be nice to have a hotkey to show/hide the leveling guide.

I don't exactly remember why (I'd have to check, there was a technical reason), but the guide-panel only refreshes/progresses if it's actually on screen. So if the user frequently hides it, progress might desync if it's not toggled back on when transitioning between zones.

**Comment by Lailloken** [comment]
I came up with a compromise-solution for v1.50 (which will hopefully be ready for next league):
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/3e9511bb-cfc2-46d0-912b-779d5f850012)
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/9c70c109-25c7-406d-ac4b-5444d2d25dc6)

There will be a configurable fade-out timer to make the overlay almost completely transparent. By default it will fade back in while holding the TAB-key (configurable), but there's also an additional option to make it fade-in on mouse-hover. Additionally, it will fade in whenever it switches to the next page in the guide, which then restarts the fade-out timer.

Let me know what you think, and feel free to suggest additional improvements.
