### ISSUE TITLE
Suggestion of item-info table: read from left to right, instead of from right to left.

### ISSUE THREAD

**Issue by LuckyTianTian2** [Lailloken/Lailloken-UI#257]
Is there a reason why all important info is on the right, and why should the base stats be read from right to left? It seems counter-intuitive.

For example, the 58% in the following image is the blue/ES value on the right, instead of the red/Armour value on the left, which is very confusing to read:
![Snipaste_2023-07-29_11-56-31](https://github.com/Lailloken/Lailloken-UI/assets/140843177/97044f21-a53b-45f9-97df-825472d9eb00)
Additionally, the grey back ground bar of 58% touches the left red armor icon, and has a gap to the right blue ES icon, which made it even more counter-intuitive.

**Comment by Lailloken** [comment]
I don't remember why I did it like this, must have been because it was easier code-wise. But yes, I am changing that for the v1.50 overhault (which is almost ready):
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/3fcdfde3-e07a-4b25-8430-cacb758c7b1f)

**Comment by LuckyTianTian2** [comment]
This looks way better. Thanks a lot.
