### ISSUE TITLE
GGG contact?

### ISSUE THREAD

**Issue by BoB3R** [Lailloken/Lailloken-UI#261]
Hello,

I've read on reddit about your tool and it looks amazing. I've saw that you wanted to contact GGG about it but didn't came back with it. Did you managed to get a hold of them and what they think about it? I didn't checked every features but this one in my opinion stands out the most in levelling "includes zone-layout overlays for many campaign-areas" as bannable. Anyways very good job!

**Comment by igloo15** [comment]
You can look up zone layouts online and many people just memorize them so overlaying them in game should not be bannable. Also most zones have multiple layouts so you would get multiple overlays and won't be sure which exactly is being used.  See https://github.com/Lailloken/Lailloken-UI/issues/237#issuecomment-1623630129 for what zone layouts are

**Comment by Lailloken** [comment]
As igloo15 said, these are just images that the tool overlays onto the screen. They are from [this guide](https://docs.google.com/document/d/1sExA-AnTbroJ-HN2neZiij5G4X9u2ENlC7m_zf1tqP8/edit), and all I did was extract them and tag them with the correct area-ID that is freely accessible via the client.txt log-file (which GGG says is fine to use).

I think I wanted to ask GGG about (de)buff tracking in the past, but then realized that this concept would be too abusable. I guess I was too excited back then.

**Comment by BoB3R** [comment]
Cool, thanks for replays!
