### ISSUE TITLE
Missing stats on contract info

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#263]
Contract info panel completely ignores the modifiers that reduce player resistance per alert level. They are not in the list of effects or among the bars on the bottom.

Example: five mods, one is -fire res per 25% alert.
![изображение](https://github.com/Lailloken/Lailloken-UI/assets/6707627/31f48bd9-b3f8-4cd3-b430-bdf7b1a88da4)

**Comment by Lailloken** [comment]
As always, very much appreciated. I can confirm this, and it generally seems to affect every "per alert level" mod. I'll look into it.

**Comment by worldendDominator** [comment]
I think things that affect the player should be in player section, even if they are tied to heist mechanic. Same about monsters, mods that apply to guards or reinforcements should be there. Heist section should be for mods that interact with the mechanic itself, like instant lockdown and alert over time.

**Comment by Lailloken** [comment]
Added the fixes and changes to v1.50.1, but the included updater was broken. You'll have to update manually to get the changes (and a fixed updater).
