### ISSUE TITLE
Recurring error message

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#265]
![изображение](https://github.com/Lailloken/Lailloken-UI/assets/6707627/d8bc25af-317f-40f4-aefb-2923c75f3bd5)
This message pops up every so often while I'm heisting, once or twice per area. Not sure if it's specific to heist or general.
I have enabled map tracker, side areas, kill tracker, and map panel mods. Loot tracker is disabled.

**Comment by Lailloken** [comment]
Hmm, this one and the map-log viewer will be harder to check remotely. I'll look into them once I'm home.

**Comment by Lailloken** [comment]
This could be an issue where the tool tries to toggle a window/overlay that has already been destroyed by something else, but I can't say for certain because I haven't encountered it yet. I'll keep looking.

Thanks again for all your help, you're a real MVP.

**Comment by Lailloken** [comment]
Added the fixes and changes to v1.50.1, but the included updater was broken. You'll have to update manually to get the changes (and a fixed updater).
