### ISSUE TITLE
Feature Request - Add base tier components to list of prioritizable archnemeses

### ISSUE THREAD

**Issue by Biggoron144** [Lailloken/Lailloken-UI#27]
This would be useful for individuals farming components to sell completion, such as in the archnemesis III challenge. It probably has other use cases as well.

**Comment by Lailloken** [comment]
I actually took that out because of UI space concerns, but now there's the ability to resize the UI. I also didn't consider challenges at all because I usually don't do them. Thanks for the feedback, I'll put it back in.
