### ISSUE TITLE
Search-Strings Not Working 

### ISSUE THREAD

**Issue by benny132** [Lailloken/Lailloken-UI#273]
Tried doing the Gwennen example on the wiki the calibration came up fine took the screenshot of the Gamble text however the test fails.

tried adding another one of the Purchases screen when visiting the vendor and even though the screenshots are being take the test continues to fail and nothing happens when pressing the middle mouse button.

Screen resolution is 1440, the other screen checks for Gamescreen and Inventory work fine.

Running the latest 1.50.1 Beta

**Comment by Lailloken** [comment]
Are you using any form of graphical filter such as ReShade, Nvidia GFE, or Windows Auto-HDR? Also, are you running windowed fullscreen at 2560x1440 or some kind of custom resolution?

**Comment by benny132** [comment]
apologies it was being blocked by the overwolf application i assumed because the other screen calibrations passed that it was something related to the ahk scripts

**Comment by Lailloken** [comment]
no worries, glad you found a solution
