### ISSUE TITLE
Support for new format of exile-leveling route hints

### ISSUE THREAD

**Issue by naviarnavi** [Lailloken/Lailloken-UI#274]
Commit https://github.com/HeartofPhos/exile-leveling/commit/93ab141aa35ad3e90ad5f32a164fdbf07e0be114 of exile-leveling added new route hints but also changed the way they are formatted.

Currently the Lailloken leveling tracker does not show the route hints. Need to parse the new format and display the hints.

**Comment by Lailloken** [comment]
Yes, I started working on it today. I wasn't given a heads-up prior to release and I had to finish some other stuff I wanted to have ready for league-launch. The update should be ready tomorrow if everything goes okay.

**Comment by Lailloken** [comment]
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/2d266366-7bbd-4757-bdc2-72348b171735)
That's what it looks like right now. If you have any ideas or suggestions, feel free to leave them here.

**Comment by Oxleyjus** [comment]
looks good, cant wait for new release.

**Comment by Lailloken** [comment]
v1.50.2 now supports the new hints in exile-leveling. Please read the release notes to find out how to re-import guides properly (when not starting a completely new campaign-run).
