### ISSUE TITLE
Notepad (1.50.1)

### ISSUE THREAD

**Issue by Fleymour** [Lailloken/Lailloken-UI#275]
hey 

for the visuals would be cool if we have the option for no background (transparent) / white / black ..

also while removing a note and i hold the button to long i got these... minor thing... but yeah wanted to show it ^^
![AutoHotkey_gcxVyf6ehZ](https://github.com/Lailloken/Lailloken-UI/assets/74535695/2ddd21d2-8417-413e-81a8-0dfe89acd31c)

**Comment by Lailloken** [comment]
Yeah sure, I can add some form of customization in the near future.

**Comment by Lailloken** [comment]
Ah, I see what you did. You dragged a tab out and immediately removed it before letting go of the left mouse-button. That's an oversight I can easily fix. Thanks for reporting.
