### ISSUE TITLE
Conflict between leveling timer and info from exile leveling in 4k

### ISSUE THREAD

**Issue by sclient** [Lailloken/Lailloken-UI#285]
The timer sits on top on the bottom section of the EL info, and I cant find any way to move the positions.

**Comment by sclient** [comment]
[https://imgur.com/a/3Hp3ZEK](url)

**Comment by Lailloken** [comment]
These two panels are designed to "share" the same space, and it looks like a conflict if the timer is stopped. As soon as you start the timer, it will hide and the buttons will become available. They behave that way because if the timer is stopped, there is no need to switch pages in the guide.

**Comment by Lailloken** [comment]
I can't replicate the timer being offset. Are you using regular 3840x2160?

**Comment by sclient** [comment]
Yup. Could it be my scaling settings? They are at 150%.
