### ISSUE TITLE
Snipping Tool Calibration Not Working

### ISSUE THREAD

**Issue by GonePh1shing** [Lailloken/Lailloken-UI#290]
Whenever I go to do a calibration that uses the windows clipping tool, the tool opens and I can use it to capture a portion of my screen, but the file isn't saved to the recognition folder as expected.

I have checked that the clipping tool is working normally by pasting into paint straight after, and have verified that the image is being saved to the clipboard. I have also run LLK-UI with admin privileges just in case the tool requires this to grab clipboard data, but that doesn't appear to change anything. Not sure what other troubleshooting steps I can take here.

**Comment by Lailloken** [comment]
In the <general> section of the settings menu, there's a write-permissions test that also tests if the script is able to create image-files. You can check if that step also fails there.

**Comment by GonePh1shing** [comment]
That seems to pass without any issues.

![AutoHotkey_awZVm70DUg](https://github.com/Lailloken/Lailloken-UI/assets/27811542/0bfd80c5-52ac-4648-8307-2c7215c7ef49)

**Comment by Lailloken** [comment]
I just edited my previous reply, see above

**Comment by GonePh1shing** [comment]
Confirmed my clipboard is indeed getting flushed. Cannot Ctrl + V the text after a calibration is initiated.

Note: I am using the Win + V feature in Windows. Would this interfere with the calibration function in the script?

**Comment by Lailloken** [comment]
I just double-checked that, and it still works with clipboard history enabled.

Could you open the `settings menu.ahk` file in the `modules` folder with a text-editor and search for this line:
`Gdip_SaveBitmapToFile(pClipboard, "img\Recognition (" vars.client.h "p)\GUI\" control ".bmp", 100)`
and replace it with this
`MsgBox, % Gdip_SaveBitmapToFile(pClipboard, "img\Recognition (" vars.client.h "p)\GUI\" control ".bmp", 100) ", " vars.client.h`
Then save and restart the script. If you now do calibration, a text-box will appear and show the error-code.

I'll probably have to implement better debugging features because some exotic issues have been cropping up lately.

**Comment by GonePh1shing** [comment]
Speaking of exotic issues...

No message box with that substitute code:
![image](https://github.com/Lailloken/Lailloken-UI/assets/27811542/cc293dd7-790f-4412-ab57-ff52a8e55049)

Closed the script entirely, made the edit, saved the file, then loaded the script again. Went to do a calibration and nothing. Whatever it is seems to be failing before it gets to that else statement.

**Comment by Lailloken** [comment]
Okay, time for some sanity-checks:
- it's the calibration in the `screen-checks` section of the settings, right? (as opposed to Betrayal or cheat-sheets or something else)

- when you click `cal` and exit out of the windows snipping tool as soon as possible, there should be a tooltip "screen-cap failed"
  - does this tooltip really show up immediately, or ist there a measurable delay? The script waits for the snipping tool to close, but if it can't properly recognize it, it will just time out and display the error-tooltip underneath the frozen screen.
- to double-check click `cal` again, wait 5 seconds and close the snipping tool. The same error-tooltip should show up immediately after exiting out of snipping

**Comment by GonePh1shing** [comment]
1: Yes, in the screen-checks section
![image](https://github.com/Lailloken/Lailloken-UI/assets/27811542/2b4735ef-713c-41f2-9b08-822c1e8a2d53)

2: Yes, I see that pop up. It shows up more or less immediately (Maybe 2-400ms or so if I had to guess)

3: This one fails. No error tooltip after a 5s+ wait.

**Comment by Lailloken** [comment]
Okay, that means the script can't tell whether or not the windows snipping tool is active or not (which could mean there are different versions of it, idk). So if you now click `cal` and immediately snip some random small area close to the cursor, it should save that image (there's a 2-second window where the script just waits, regardless of the snipping tool's state).

Now, to find out why it cannot recognize the snipping tool:
- right-click the script's system tray icon and open the `Window Spy` tool

- make sure `follow mouse` is unchecked in the top-right corner
- press Win-key + Shift + S to open the snipping tool, then exit out
- the window spy should show info on the window that was active most recently
  ![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/7377b384-34ba-4bb1-a809-d741f0d19507)

**Comment by GonePh1shing** [comment]
So, confirmed, it does actually capture the image if I'm within that short window before the check is made.

Problem is the Window Spy tool only flashes up the details you want me to catch for an extremely short time (<1s), before going mostly blank (See below). Any suggestions?

![image](https://github.com/Lailloken/Lailloken-UI/assets/27811542/4c88542a-b874-40b7-a15e-a18389c37c70)

**Comment by Lailloken** [comment]
Holding shift should prevent the window spy from refreshing. So hold shift while the snipping tool is open, then close it, and the windows spy should show the correct info.

**Comment by GonePh1shing** [comment]
And just as I posted that, I managed to actually grab it in the .1 of a second it's actually on screen:
![image](https://github.com/Lailloken/Lailloken-UI/assets/27811542/afa74e90-3f8e-485f-88ab-4677d8b162a6)

I suspect the issue is because I'm on an old Windows build (Ver 1809, Build 17763.4737), which likely contains an older clipping tool version.

**Comment by Lailloken** [comment]
I see, that explains a lot. You could temporarily replace the current exe-identifier `ScreenClippingHost.exe` with `ShellExperienceHost.exe` in the `screen-checks.ahk` file within the modules folder. I'm currently busy untangling some oofs I made with multi-monitor stuff, but I'll make the necessary changes for your issue asap.

**Comment by GonePh1shing** [comment]
Thanks, that workaround solves the issue!

No need to prioritise the fix as you can probably count the number of users that may ever experience this on one hand (Hell it might literally be just me). Guess it serves me right for running Win10 LTSC, but this is genuinely the first issue in like 4 years I've come across that's been caused by this.

**Comment by Lailloken** [comment]
Glad it works, what a journey. The exe-identifier is also present in `Lailloken UI.ahk`, `betrayal-info.ahk`, `cheat sheets.ahk`, and `settings menu.ahk`. So if my fix takes too long to be ready and you run into more calibration issues, that's where it needs to be replaced as well.
