### ISSUE TITLE
F5 changing resolution settings.

### ISSUE THREAD

**Issue by Puandro** [Lailloken/Lailloken-UI#293]
Cant find the option to disable this.

**Comment by Lailloken** [comment]
Nothing is bound to F5, and there's no such feature to change resolution settings on-the-fly. What exactly happens when you press it?

**Comment by Puandro** [comment]
So the issue was using F5 while having Awakened Trade was changing my resolution from full screen windowed to full screen and making my resolution custom. F5 on Awakened Trade is /hideout + enter. I just disabled the option on Awakened Trade. This was not an issue before with version 1.3.

**Comment by Lailloken** [comment]
Pressing ALT + Enter usually does that. It could be that the state of your ALT-key was stuck somehow. You're the first to report this behavior, so I'm not sure it's necessarily connected to v1.50.
