### ISSUE TITLE
Edge case lab overlay

### ISSUE THREAD

**Issue by ShadowWisp** [Lailloken/Lailloken-UI#296]
[merciless-2023-08-22.txt](https://github.com/Lailloken/Lailloken-UI/files/12408299/merciless-2023-08-22.txt)
![image](https://github.com/Lailloken/Lailloken-UI/assets/27205923/1866d02f-31dc-4f60-a3ea-b2fe53683576)
Edge case of lab overlay borking due to the fact that room 3 and 5 in current merc lab were called Estate Path.
![image](https://github.com/Lailloken/Lailloken-UI/assets/27205923/5039993f-446c-4cb7-a7f2-fc87db03f28e)
1st image is raw file from poelab, 2nd is screenshot taken in Aspirant's lab room №8. 
How to replicate: Boot a labyrinth into a state where entrance to trial will be the same name as the room after one.

**Comment by ShadowWisp** [comment]
Textfile attached was initially poelab compass file of .json format. Github doesn't allow .json files, i renamed to .txt

**Comment by Lailloken** [comment]
Thanks for reporting and including this much information. This layout exposes quite a few oversights, and I'll have to do some re-thinking. I'll probably also add some form of manual override in order to simply jump to the next room in case the script gets stuck.
