### ISSUE TITLE
Super slow scanning in the newest version

### ISSUE THREAD

**Issue by Aldwew** [Lailloken/Lailloken-UI#3]
1.14.1 works just fine. 1.14.2 Takes multiple seconds to scan 1 image.

**Comment by Lailloken** [comment]
Which resolution are you running? I can't replicate this on my end. The only time I experienced such slowdowns was when another AHK script caused high load. Also, the script pauses whenever it or the PoE client lose focus. If continuously clicking on the PoE window while scanning solves this problem, that would be the cause.

**Comment by Lailloken** [comment]
Can you check the properties of your img\Recognition folder and tell me how many files it contains?

**Comment by Aldwew** [comment]
It has 45 files in it.

**Comment by Lailloken** [comment]
Hmm, you could try going to the end of the folder structure of Recognition and see if there are any corrupted files (either the image files themselves or the file name). The difference between 1.14.1 and 1.14.2 is related to skipping file checks.
