### ISSUE TITLE
No map suggestions for base mods.

### ISSUE THREAD

**Issue by faraddox** [Lailloken/Lailloken-UI#30]
![image](https://user-images.githubusercontent.com/12736024/155974933-10f04711-78bb-408d-8b03-15c9fcde5625.png)
No maps suggested when you chose just base mods, not recipes. If map search was implemented only for recipes, than count this as suggestion :)

**Comment by Lailloken** [comment]
Yeah, woopsie. I recently re-added the ability to add base mods to the prio-list, but then forgot to adapt the optimal drop locations to apply to them as well. There should be a new release today once I get home -- only a few finishing touches left -- and I'll include this.
