### ISSUE TITLE
Custom resolution snaps game client to secondary monitor

### ISSUE THREAD

**Issue by rompwow** [Lailloken/Lailloken-UI#300]
I have three monitors. The center monitor is marked as my primary monitor in windows. 
I am usually playing with a resolution of 2560 x 1230, which I wanted to apply with Lailoken UI as well. 

However, when I try to set any solution in the settings menu, the games is snapped to my left monitor. 
Is there any way to fix this? 

Possible reproduction:
1. start poe
2. start lailloken ui
3. set a custom resolution of 2560 x 1200 (or any other resolution, bugs out with any for me)
4. client is moved to left monitor

**Comment by Lailloken** [comment]
I can replicate this behavior in windowed mode and I'll look into fixing it. Is your primary monitor 2560x1440? If so, you can set the game to windowed fullscreen instead of windowed mode (make sure to click `save` in game), then restart the script and apply 2560x1200.

**Comment by Lailloken** [comment]
Fixed in v1.50.6
Thanks for reporting.

**Comment by rompwow** [comment]
What a banger speed, thank you for fixing it! Works like a charm.
