### ISSUE TITLE
Betrayal-Info tool is misscoloring rewards

### ISSUE THREAD

**Issue by Vladislav-Lyuminarskiy** [Lailloken/Lailloken-UI#305]
Betrayal-Info tool doesn't respect chosen reward-colors tier in the top bar.

Here is some examples of this:
- Guff is white but should be red ![image](https://github.com/Lailloken/Lailloken-UI/assets/16743037/505b48ec-8b6f-4c1f-a623-c291c87df09b)
- Vorici is red but should be yellow ![image](https://github.com/Lailloken/Lailloken-UI/assets/16743037/a2e8143f-9fa3-4cb7-a533-7c4bdcdf31f4)
- Riker is green but should be yellow ![image](https://github.com/Lailloken/Lailloken-UI/assets/16743037/f8ea635e-1aca-41b0-91af-e86715c1dad3)

**Comment by Xalatesh** [comment]
also the screen seams to be buggy, when pressing the omni key while hovering over a unit the screen just flickers, only when i press right mousebutton and omni key multiple times i can make a screenshot of the character

**Comment by Lailloken** [comment]
The color in the overview represents how good the current position/reward is:
- green: the current reward is optimal, i.e. this syndicate member doesn't have better rewards elsewhere

- red: the current reward is bad in comparison, i.e. there are better rewards elsewhere
- white: the current position is as good as any

So basically it's `stay`, `move`, `doesn't matter`.

**Comment by Lailloken** [comment]
> also the screen seams to be buggy, when pressing the omni key while hovering over a unit the screen just flickers, only when i press right mousebutton and omni key multiple times i can make a screenshot of the character

@Xalatesh I think that's an incompatibility that's cropped up recently. I've received a few reports of Win11 users who had this flashing issue. Switching the game's renderer to DX12 seems to fix it.

**Comment by Vladislav-Lyuminarskiy** [comment]
> The color in the overview represents how good the current position/reward is:
> 
> * green: the current reward is optimal, i.e. this syndicate member doesn't have better rewards elsewhere
> * red: the current reward is bad in comparison, i.e. there are better rewards elsewhere
> * white: the current position is as good as any
> 
> So basically it's `stay`, `move`, `doesn't matter`.
> 
> EDIT: In the case of Riker, it's easier to see that he's in the optimal position. Highlighting it yellow it the overview wouldn't be clear-cut and you'd have to manually check his global rewards.

Thanks for the clarification!
