### ISSUE TITLE
[Possible incompatibility] Screen flashes when pressing omni-key

### ISSUE THREAD

**Issue by Lailloken** [Lailloken/Lailloken-UI#306]
I have received a few reports about the omni-key (and screen-check testing) causing screen flashing/flickering. One thing these users had in common was that they are using Windows 11. We figured out that setting the game's renderer to DX12 resolves the issue.

**Comment by Xalatesh** [comment]
So does that mean you have to play on DX12 in Win11 if you want to use Lailloken? 
What about Windows 10? will it work in DX11 there? because DX12 sucks on W11 for me and it weardly jumps around 80 fps where Dx11 gets 120+ since the engine update.

**Comment by Lailloken** [comment]
I tested every renderer on Win10 and didn't have this flashing problem. But I'm not sure if the problem is Win11 itself, or if it's some software/hardware combination that's causing the issue. I think I only received four reports of this behavior, which is not enough considering the Win11 user-base (or everyone on Win11 happens to use DX12).

Have you tested DX12 for a longer period? It's possible the inconsistent performance you're experiencing is due to shader compilation, which may resolve after playing for a bit.

**Comment by worldendDominator** [comment]
What kind of flashing are you talking about? I've seen something I could describe as that, but I wasn't sure if it's related to the UI at first. Initially, game window would rapidly flicker for about a second, showing my desktop icons on top of it; the game's visuals also freeze during those flickers. More recently, it's been just the UI-specific icons (main menu, notepad, map tracker) flickering on and off instead, without the game itself.

**Comment by Lailloken** [comment]
@worldendDominator someone uploaded a clip in #279, it's a short full-screen black flash.
I very rarely encountered things like this (I recreated the issue in a photo-editor):
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/bdb7d801-dc34-4d32-8b58-9145f45a477d)
But it was usually after changing window-mode and resolution back and forth when testing compatibility, so I thought it was just related to that.

**Comment by Xalatesh** [comment]
> I tested every renderer on Win10 and didn't have this flashing problem. But I'm not sure if the problem is Win11 itself, or if it's some software/hardware combination that's causing the issue. I think I only received four reports of this behavior, which is not enough considering the Win11 user-base (or everyone on Win11 happens to use DX12).
> 
> Have you tested DX12 for a longer period? It's possible the inconsistent performance you're experiencing is due to shader compilation, which may resolve after playing for a bit.

after playing with DX12 for a longer period it became stable ^^ just a bit lower fps but gsync handles that xD now i can use the betrayl again
