### ISSUE TITLE
Getting error: "Unable to locate the appropriate interpreter to run this script." on version 1.50.7-beta.

### ISSUE THREAD

**Issue by ljrobison** [Lailloken/Lailloken-UI#307]
I wasn't sure where else to post this so remove if it isn't the right place.

But I downloaded the newest version, deleted the folder for the previous one, and went to launch it and am given the following error:

`Unable to locate the appropriate interpreter to run this script.`

`Script: Lailloken UI.ahk`
`Requires: >=1.1.36 <2`

If anyone could point me in the right direction on how to remedy this it would be appreciated. I tried googling the error, but only seemed to get results related to other random projects.

**Comment by Lailloken** [comment]
v1.50.x requires AutoHotkey version 1.1.36 or newer, but it cannot run on AutoHotkey v2. If you have AHK v2 on your system, you'll need to install v1 as well. If you already have v1 installed, you'll have to update it to at least 1.1.36
https://www.autohotkey.com/download/

**Comment by ljrobison** [comment]
> v1.50.x requires AutoHotkey version 1.1.36 or newer, but it cannot run on AutoHotkey v2. If you have AHK v2 on your system, you'll need to install v1 as well. If you already have v1 installed, you'll have to update it to at least 1.1.36 https://www.autohotkey.com/download/

Thank you so much! The was simple enough. Appreciate the quick response as well.
