### ISSUE TITLE
Betrayal reward is outdated

### ISSUE THREAD

**Issue by vudinh29** [Lailloken/Lailloken-UI#308]
This seems odd, I'm not entire sure if it's my fault but the Betrayal rewards are from ~2018? I checked the Betrayal.json to confirm and it's indeed outdated there.

**Comment by Lailloken** [comment]
Could you be more helpful and provide examples? You're making it sound like the rewards are wildly inaccurate. I double-checked with the wiki and only found three (minor) discrepancies:
- Haku fortification: strongboxes -> unique strongboxes

- Haku research: quality rare items -> quality weapons/armors
- Riker research: oils were missing in the selection from which to pick one

**Comment by vudinh29** [comment]
Sorry, didn't mean to sound rude. I discovered the issue when looking at Vorici to find the white socket reward, and was confused when his rewards were applying chrome/jewellers/fusings for T/F/R. I did a search for that and the results were circa 2018 when the league first launched. Another examples is Korell: T/F/R is Helmet/trappedcrafting/timed crafting; as of 3.20 (cheatsheet I found linked below) it should be Essence/Map frags/Fossils. 
[Cheatsheet](reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fw9gu4tqsj7va1.png%3Fwidth%3D1800%26format%3Dpng%26auto%3Dwebp%26s%3De59ddf28c5eb0a1bc4c9cd37e863b2e170bfea2b)

[Korell ](https://www.poewiki.net/wiki/Korell_Goya,_Son_of_Stone)wiki

I think the dead giveaway is that I pretty sure timed crafting was removed from Betrayal rewards a awhile ago?

**Comment by Lailloken** [comment]
No worries, happens to the best of us.
