### ISSUE TITLE
show amount of completed items

### ISSUE THREAD

**Issue by pvgoddijn** [Lailloken/Lailloken-UI#31]
if you have time/feel like it, I would be very pleased if a counter could be added for how many of the items you already have

This is useful to know if I should build more of (especially) the intermediate types or if I  can burn some 'needed' recipes
(like if I have 6 frost striders I might want to burn a few to make space in the inventory, or if I only have 1 invulnerable I might want to already make a second)

Any way great tool, and a big improvement over the native one. i was actually skipping the mechanic before I found this tool so thanks a lot :1st_place_medal:

**Comment by Lailloken** [comment]
Clicking the PRIO-label opens a surplus list which should also calculate the surplus in intermediate mods (please tell me if it doesn't). To balance out branches, you can hold-click a recipe in the prio-list to see a tree-view with the quantities of base and intermediate mods.
If a different kind of list/counter could be beneficial, please let me know and also specify. I need to know how a feature should work and could be helpful/useful before I implement it (I don't always understand it from a concept alone, I need to 'see' the train of thought).

**Comment by pvgoddijn** [comment]
I saw what yoou mean and that is nice i think a counter IN the prio list would be nice though (so you can see at a glance how many of the prio ones you have ready and wether you can 'waste' some while building up to a larger combination

(i mean the green ones in the top)

**Comment by Lailloken** [comment]
Alright, there'll be an update in an hour or so that revamps the UI a bit and covers what you suggested. Just needs a little bit more testing. Thanks for your feedback.
