### ISSUE TITLE
Update required AHK version info

### ISSUE THREAD

**Issue by niquilz** [Lailloken/Lailloken-UI#317]
> it also requires AutoHotkey 1.1.36 or newer:

Alright my ahk is way old, so I update to latest nonalpha, 2.0.1.  Download your sources, run .ahk "Unable to locate the appropriate interpreter to run this script. Requires >=1.1.36 <2".

I propose changing wherever it is noted that AHK 1.1.36 is required, this be updated to include "and below AHK 2.0".  That would be decent of you, thanks.

**Comment by tayata369** [comment]
"Unable to locate the appropriate interpreter to run this script. Requires >=1.1.36 <2". I get this problem and how to fix it ?

**Comment by tayata369** [comment]
thanks
