### ISSUE TITLE
Detected Language "Not Supported" after update to 1.51

### ISSUE THREAD

**Issue by C-quintana** [Lailloken/Lailloken-UI#331]
Today I used the inbuilt updater to update the tool to 1.51 from 1.50.9 (I think it was this version) and now I receive a red error in the settings menu:
![image](https://github.com/Lailloken/Lailloken-UI/assets/64966501/63ea17ea-c131-4c56-9680-026ab58783d5)
Hopefully visible in the image here.

I have so far restarted the ahk script, restarted the game, unset and set the language to anything but English and back again, but all seem to give me this same error message.
It is not disabling anything I frequently use on the ahk script, mainly utilise the exile levelling integration and that appears to work fine, but this could be an issue for other users who utilise the tools disabled by not having a language pack (Item Info I think is one that gets disabled)

**Comment by C-quintana** [comment]
Comments to add after a bit more messing around:
1. Refreshing game settings on the main options didn't work.
2. deleting and redownloading the latest release didn't work.
Following step 2 then step 1 though did resolve in the game language being detected correctly. So If anyone else has this issue:

redownload the latest release then click on this button:
![image](https://github.com/Lailloken/Lailloken-UI/assets/64966501/8919eebd-4560-44ef-9b57-3b5d8896768d)

**Comment by Lailloken** [comment]
The tool actually checks the in-game language by reading the games client.txt log-file and searching for the "You have entered..." line, and each language pack has the corresponding version of that line. Whichever version of the line was found closest to the end of the log-file determines which language the client is currently running on.

I tried replicating this issue by re-installing a v1.50.9 build and using the updater from there, but it worked without issues.

Were you already in game when you used the updater, or were you updating while on the login screen?

**Comment by KamilChowaniec** [comment]
Hi, i have the same problem, but i just downloaded the newest version, without using the updater.
In my Client.txt there is for example: "You have entered The Sarn Encampment." line, but it shows that the detected language is not supported.
Can i somehow manually set the language?

**Comment by Asyrin** [comment]
I'm having the same problem. I can get it to kind of work, by closing the script, closing the game, restarting the game, then restarting the script as admin. It then shows that it's detecting the language is English, but it doesn't really work still. 

For example, I start the game, load the script, it says it detects the language is English and everything looks good. So it should be working, but when I try to enter a character it either can't find the character (shows the feature as being yellow) despite me making sure I spelled it right and leveling up multiple times to see if it would catch up or something, or it finds the character (feature is green) but it gives the wrong level, It currently says my one character is level 48 despite only being level 5 and another being 33 despite being 50, along with one character that it just can't find. When I try to restart the script (right clicking the LLK-UI button) then it goes back to saying Detected Language: Not supported and I have to start all over again

**Comment by Lailloken** [comment]
> It currently says my one character is level 48 despite only being level 5 and another being 33 despite being 50

Are those character-names that you had also used in past leagues?


If you're OK with sending me parts of your game's client.txt, I will be able to take a closer look into this: It contains some information about your hardware, as well as messages that were on display in the chat-box. I'm only interested in the structure of the data, and why the tool is behaving this way.

If you're fine with sending it over, open `GAME FOLDER\logs\client.txt` and search for `XYZ (CLASS) is now level 2`, with XYZ being the name of your first character this league and CLASS being their class (assassin, ranger, templar, etc.). Copy that line and everything up to the end of the file, paste it into a new txt.file, and attach it to a response here or add me on Discord (lailloken) and send it to me there.

**Comment by Asyrin** [comment]
[Part of Client.txt](https://github.com/Lailloken/Lailloken-UI/files/13626874/Part.of.Client.txt)
As far as I can remember I haven't used this name for a character before, but it's possible. I usually try to use some variation of a few names that I tend to stick with. I know I used Asyrin in the past, and I think I used Assyrin, but I don't recall using Asyrrin, which is what this character was named. I'm just too lazy to think up new names every league. And I know for a fact that the character that isn't being recognized (Ysaeviel) has never been used before. anyway, hope this helps

**Comment by Lailloken** [comment]
v1.51.2 contains a fix for these language-detection issues.
@Asyrin: Thanks for providing parts of your log-file.

From what I can tell, the previous implementation failed whenever the `client.txt` log-file was "cluttered" with error/patch messages, or when the client had previously crashed while transitioning between areas. There were instances where about 40 lines of debug/error messages were logged within around 10 seconds after loading into a zone.

**Comment by Asyrin** [comment]
the only time I can think of when the game crashed a lot was during the first day when zoning to town crashed it like 50% of the time. Anyway, the language detection seems to work with the new version so thank you for that! However, it's still having the issues when trying to find the character. It's not really a big deal since it's more for convenience. Just figured I'd give you a heads up.
