### ISSUE TITLE
Desktop flickering through game

### ISSUE THREAD

**Issue by data54** [Lailloken/Lailloken-UI#336]
Not sure if this is a known issue or related to the script but I'm having random flickering of my desktop through the game, the screen spazzes out and I see the outlines of my icons and stuff and then it goes back to normal, it happens a few times an hour.

Specs:
- Windows 10
- 3080 Ti
  - Latest driver
- 2560x1440
  - 3 monitors with the same resolution, game runs on the main monitor
  - DX11
  - VSync off
  - Windowed Fullscreen

**Comment by Lailloken** [comment]
I think I have only heard of that once. How many of these features do you have activated: leveling tracker, mapping tracker, notepad, clone-frames? If you are using clone-frames, how many have do you have set up and what do they look like (position, size, etc.)?

I want to know how many overlays are active on your end, so I can try replicating this issue. The easiest way to find out if it's script-related would be playing a session without it.

**Comment by data54** [comment]
The only overlay I'm currently using is the leveling tracker.

I don't know if it could impact it but my KB/Mouse and one of my monitors is going through a TESmart KVM, the main monitor that I play games on I switch input on directly though.  I'll try to see if maybe it's caused by micro stutters on the KVM or something later tonight by going directly into the pc.

**Comment by data54** [comment]
I ran display driver uninstaller and verified the game cache and didn't run into the issue in the few hours I played last night, I have had random crashes but haven't had a chance to try without running the script so that might just be the game itself, seems like it might have been an issue with my install/drivers.
