### ISSUE TITLE
Restore Clipboard Content

### ISSUE THREAD

**Issue by aasmall** [Lailloken/Lailloken-UI#348]
I keep a regex on my clipboard while leveling to check various vendors for links and move speed boots, etc. I also love the leveling overlay feature. However, when I use the omni key to search for gems to buy in each town, it clears my clipboard and I need to alt-tab to grab my old regex.

Could you capture the content of the clipboard before overriding it with the omni-key, search for gems feature, and then restore it afterwards? alternatively, could you support a non-clipboard based input for the gem search regex?

**Comment by Lailloken** [comment]
I'm kind of paranoid when it comes to (temporarily) storing clipboard contents. I don't want any code that interacts with the clipboard to be taken out of context. People who review code (or use tools for that) before downloading/using it may look for specific patterns.

You can check out my [search-strings](https://github.com/Lailloken/Lailloken-UI/wiki/Search-strings) feature as an alternative solution. It lets you create context-menus that are accessed via the omni-key:
![image](https://user-images.githubusercontent.com/61888437/214895726-1a1c93d9-7183-40ca-bd6d-2da446169286.png)

Each entry in the menu will paste a regex that you set up, and you can create menus for basically every individual search in the game. If only one entry is present, the regex will immediately be pasted upon pressing the omni-key, without showing the context-menu.

**Comment by aasmall** [comment]
It mostly works. The problem is that when I'm running through town, I need to talk to both the gear vendor to check for things as well as the gem vendor. Since all vendors looks the same(ish) and I may need to check the gem vendor for a wand, it's ambiguous which I want to occur, gem search or gear search. if the step of the leveling process calls for a gem search, I have to tick forward to the next step in order for search-strings to trigger. It's a bit annoying. 

a potential solution would be that if both the leveling tracker gem search AND the search-strings image checks occur, let me pick like you do for multiple search-string matches.

**Comment by Lailloken** [comment]
There's a subtlety that's easily overlooked which causes the ambiguity. The gem-search from the leveling tracker is activated by `holding` the omni-key, search-strings by tapping it. That's how I made sure they don't overlap, yet can be activated by a single hotkey.

**Comment by aasmall** [comment]
Thank you for all your help the difference between click and hold was lost on me, but it works great. The only problem I have now is the HDR issue, which is tracked under [351](https://github.com/Lailloken/Lailloken-UI/issues/351).
