### ISSUE TITLE
Unable to locate the appropriate....

### ISSUE THREAD

**Issue by Kolonelmustard** [Lailloken/Lailloken-UI#354]
AutoHotKey gives me prompt when trying to launch script. 
![Screenshot 2024-03-28 175000](https://github.com/Lailloken/Lailloken-UI/assets/165337420/666a9f4f-4201-4717-acb2-66a1365839ce)

I've skimmed the Help directory to on avail. I do apologies for the last mine request, as League start is tomorrow. If any help could be provided I'd greatly apricate it. 
![Screenshot 2024-03-28 175000](https://github.com/Lailloken/Lailloken-UI/assets/165337420/350c77f7-e3e6-47b6-8c81-ff2f2190b13f)

**Comment by Lailloken** [comment]
You might have skimmed a bit too fast
![image](https://github.com/Lailloken/Lailloken-UI/assets/61888437/67c90818-fbc6-4c3c-b1e4-6b9789a80c94)

**Comment by Kolonelmustard** [comment]
i am dumb lol ty
