### ISSUE TITLE
Weird graphical bug (Desktop breaking through PoE)

### ISSUE THREAD

**Issue by Cariyla** [Lailloken/Lailloken-UI#356]
Since a few weeks using the UI will intermittently have my desktop "break through" PoE, a small part of the left side of my PoE window where the UI settings window would normally be will randomly blink every now and then, go semi-transparent for a bit and show desktop icons/desktop background. This only happens when using the UI, not when playing PoE without it.  Hard to take a screenshot cause it happens randomly and only for half a second at a time, will try uploading a screen recording soon if possible (probably some time after league start). This only happens with the UI running, never without it. Not sure exactly when this started, may have been 1.52.2

Just updated to 1.52.4 and haven't gotten to try it yet but have confirmed this in both 1.52.3 and 1.52.2, running PoE in windowed fullscreen 1920*1080 on Win10 Enterprise 21H2, AHK 1.1.37.01

**Comment by Lailloken** [comment]
Someone reported this problem in #336. I would say it could be some form of compatibility issue (or at least something system specific) since I have not gotten many reports. Which features are you using? The issue may be caused by one feature in particular.

**Comment by Cariyla** [comment]
Only using leveling tracker and notepad

**Comment by Lailloken** [comment]
Hmm, too bad the other user didn't report back after reinstalling GPU drivers. Could mean anything. You could try reinstalling too, or maybe switch the renderer in game.

**Comment by Cariyla** [comment]
Will try both and those and report back later, thanks for the quick replies!
