### ISSUE TITLE
It takes time for the required material window to appear.

### ISSUE THREAD

**Issue by ysalpha2021** [Lailloken/Lailloken-UI#37]
When I left click on the favorites list, it now takes a considerable amount of time before the material window appears.
As of 1.21.0, this behavior was already in place.
In previous version, the material window appeared the moment the left click was pressed.
I prefer the previous behavior.

**Comment by Lailloken** [comment]
Do you mean the tree-view? Yes, v1.21.0 added a delay when I enabled prio-recipes to be clickable for highlighting. Maybe I made it too long, I'll look into it.

**Comment by Lailloken** [comment]
Reduced the delay in v1.21.2
