### ISSUE TITLE
Corpses in Necropolis

### ISSUE THREAD

**Issue by I3lvcky** [Lailloken/Lailloken-UI#377]
Heyho, loving your Script its amazing and was helping me as new player to poe alot.

For this current league is would asked if its possible to mark the corpses for crafting in the same like the Altars from Exarch/Eater.

So that you can set up corpse in different tier colour and this would make the farming for this a little bit smother cause when you see the green for sample you know thats a corpse i need for sure.

Is this possible with the OCR Feature?

**Comment by Lailloken** [comment]
I just double-checked to make sure: The "plaque" above dropped corpses looks like a special UI-element but behaves like regular dropped loot. That means you can't hover over it and then press the `toggle highlighting` hotkey (which the TLDR-tooltips feature does to hide unrelated text and improve accuracy).

Without hiding unrelated surrounding text, scanning corpses would always fail (or be inaccurate) whenever there's loot, chests, other corpses, etc. next to the corpse you want to scan.

**Comment by I3lvcky** [comment]
I See, thx for checking it anyways and the quick response!
