### ISSUE TITLE
Doryani's Invitation miscategorization

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#378]
Trying to get the unique roll popup for Doryani's Invitation instead gives a "normal and unique not supported" message. I suspect it gets mistaken for an invitation item.

**Comment by Lailloken** [comment]
> I suspect it gets mistaken for an invitation item.

Yes, that's it. Thanks for reporting. I'll fix it for the next release.

**Comment by Lailloken** [comment]
fixed in v1.53.1
