### ISSUE TITLE
Abyss jewel named "Ancient Orb" triggering stash-ninja as if in currency stash tab

### ISSUE THREAD

**Issue by MadMarbleHead** [Lailloken/Lailloken-UI#397]
A bit of an edge case here, but invoking item-info with the omnikey on a searching eye jewel named "Ancient Orb", the currency stash tab menu is invoked instead.

This occurs in [stash tabs](https://github.com/Lailloken/Lailloken-UI/assets/170190745/fc264e69-f36a-409e-909a-dfe180c4e185), [inventory](https://github.com/Lailloken/Lailloken-UI/assets/170190745/042e2a04-7c05-45df-800a-fb35781b89af), [special stash tab slots](https://github.com/Lailloken/Lailloken-UI/assets/170190745/759fc907-9360-444b-af74-e8f26812dce2), and [passive skill jewel sockets](https://github.com/Lailloken/Lailloken-UI/assets/170190745/213f5f18-8120-448a-8fd9-9d20e9fafaf4) of all types, but doesn't occur in abyss jewel sockets [in gear](https://github.com/Lailloken/Lailloken-UI/assets/170190745/e7912f54-38b6-4b8c-9f4c-5b0f13a38da7) (possibly because the clipboard accesses the underlying piece of gear instead of the jewel)

**Comment by Lailloken** [comment]
Huh, nice catch again. A hotfix is now live, and you can get it via the built-in updater. The omni-key now also checks if the item has a base-type, and only activates stash-ninja if that's not the case.

**Comment by MadMarbleHead** [comment]
Excellent! Tested, and the hotfix works on my end! Thank you for handling things so speedily!
