### ISSUE TITLE
Item-context on incubators and relics directs to nonexistent wiki pages

### ISSUE THREAD

**Issue by MadMarbleHead** [Lailloken/Lailloken-UI#403]
When using item-context to access the wiki page for incubators, it directs to https://www.poewiki.net/wiki/Incubators instead of directing to https://www.poewiki.net/wiki/Incubator. Similarly, relics direct to https://www.poewiki.net/wiki/Relics instead of directing to https://www.poewiki.net/wiki/Relic.

**Comment by Lailloken** [comment]
Hmm, the wiki usually redirects you automatically, e.g. when accessing https://www.poewiki.net/wiki/Helmets. That's why I just use the item-class that's in an item's clipboard text.

Thanks for reporting, I'll fix it for the next release.

**Comment by MadMarbleHead** [comment]
I hadn't realised that. Since the issue seems to be wiki side, I'll add a redirect to the wiki pages.

**Comment by MadMarbleHead** [comment]
I've added the wiki redirects and tested; the issue shouldn't need anything done on your side.
