### ISSUE TITLE
Act_Tracker Text Size Resetting

### ISSUE THREAD

**Issue by zefrogi** [Lailloken/Lailloken-UI#410]
Hey Lailloken,

On the latest version, I noticed that every time I change the Act Tracker in terms of profile or reset, the text size changes back to the default number.

It's not a massive issue once you're set-up, but I don't think it's intended behaviour.

**Comment by Lailloken** [comment]
Could you check if you're actually on the latest version? There was a config-bug that I fixed recently that would also prevent updates to newer versions.
![image](https://github.com/user-attachments/assets/d0a0e2a9-e832-4ce8-918c-fbf5ade2c755)

**Comment by zefrogi** [comment]
Yep, I am using the latest version.

It's on a second monitor if that changes anything. I know there was something about that in a ticket I made before.

**Comment by Lailloken** [comment]
A typo is preventing the tool from correctly loading the font-size. Until there's an official update, you can open `modules\leveling tracker.ahk` in a text-editor, search for "font_size" and replace it with "font-size".

**Comment by zefrogi** [comment]
Legend as ever, thanks man!

**Comment by Lailloken** [comment]
Fixed in [v1.53.4](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.54.3)
