### ISSUE TITLE
act tracker can get stuck off screen if resolution lowers

### ISSUE THREAD

**Issue by mrooney** [Lailloken/Lailloken-UI#411]
Hi there and thanks for this fantastic collection of tools! I use a laptop and regularly switch between a large monitor and playing on the laptop screen itself. I like to have the act tracker in the bottom middle, but when I go back to playing on the laptop monitor, the act tracker is stuck off screen and I don't know how to get it back besides editing the .ini file.

Suggestions:

- Simple: if the x/y coordinates of the act tracker are out of the screen bounds on startup, reset it to default. This way I can simply restart Lailloken to fix it.
- Best: keep a map/dict of resolutions to x+y positions so it can remember where it goes at each resolution. By the way, this would be amazing for screen checks as well, which are kinda useless if you switch between monitors/resolutions daily since you have to redo them all multiple times per day. It could remember them per resolution as well. I can file a separate issue if this is interesting to you.

Thanks again!

**Comment by Lailloken** [comment]
Also: "bottom, middle" is the default position, so right-clicking the white square in the widget should put it there at every resolution (unless you mean "bottom, middle" but slightly above the exp-bar).

**Comment by Lailloken** [comment]
> is it possible to apply the out of bounds check to the act tracker as well, that would be extra awesome!

I'll fix it for the next release. I would normally publish a hotfix for that but I'm pretty deep into implementing updates and new features for 3.25.

The way I do it is: switch monitors in the in-game settings, wait for it to switch over, then confirm in-game to keep these settings, and also click save in the in-game options. Then I just restart the tool, and it figures it out itself.

**Comment by mrooney** [comment]
Awesome, thanks! I don't use multiple monitors, just either laptop display or my ultrawide. I did try closing PoE, unplugging the monitor, reloading Lailloken, and launching PoE. Lailloken says it has to restart due to resolution changes, but when it does the Act Tracker is still off screen. For now I'll just pin the `ini` in my Quick Access so I can tweak it more easily. Looking forward to the hotfix and also your new 3.25 changes!

**Comment by Lailloken** [comment]
Should be fixed in [v1.53.4](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.54.3).
I'll leave this open for now, maybe this requires more feedback.

**Comment by mrooney** [comment]
Thanks! I installed the new version via the updater, and it rebooted. Then I moved the dialog and rebooted it (not switching monitors) as a sort of control, and ended up with the following error (and act tracker stuck) 
![image](https://github.com/user-attachments/assets/ed1c562f-7fe1-4e43-a085-27a6ed6ceb5b)

**Comment by Lailloken** [comment]
Hmm, that's an "initialization error". Basically, at script startup the script checks the position of the PoE-client, creates an invisible window in its center, then maximizes said window. This is to check which monitor the client is running on and to get the monitor's resolution and set the bounds (the exact bounds the act-tracker didn't respect when you first encountered issues).

The error states `invalid option: x y maximize`, which means it tried to place the invisible window at x-coordinate `blank` and y-coordinate `blank`. So for some reason the script couldn't retrieve the position of your PoE-window. That usually happens when launching the tool while the game is minimized or invisible for a different reason.
