### ISSUE TITLE
Suggested Links during the level progress

### ISSUE THREAD

**Issue by Rottenbeer** [Lailloken/Lailloken-UI#415]
Hi! 

Thanks for your overlay!

I'm wondering of the gem link section from exile levelling can also be shown in the overlay?

e.g. this:
![image](https://github.com/user-attachments/assets/16379f56-1412-49c6-88c5-118de4935116)

**Comment by Lailloken** [comment]
No, this data is not included in Exile-Leveling's export. I think you're the first to request this.

I just thought of an alternative, but it needs a bit of manual work (i.e. writing the list yourself):
- I have this notepad feature that lets you create text-widgets: [wiki](https://github.com/Lailloken/Lailloken-UI/wiki/Minor-Features#notepad-and-text-widgets)

- these widgets are kind of like sticky-notes you can place onto your screen

- they have an inactive and active state: basically, they're unclickable by default, and you activate them by holding TAB (that makes them clickable and thus movable)

- you can set a transparency for their inactive state, and that also includes full transparency (so invisible)

- so you can create a gem list, turn it into a sticky-note that's invisible while playing, then hold TAB whenever you want to look at it:

  ![image](https://github.com/user-attachments/assets/9868bdb2-08d4-4022-85ef-919bfddcd1a9)

If you do end up considering this, you should create the list in a real text-editor first and save it just in case. The color coding in my notepad can be jank and you might lose text if you're not careful. Also, to display a blank line, you have to put a single space in it.
