### ISSUE TITLE
Add configuration for emergency restart key combination

### ISSUE THREAD

**Issue by velit** [Lailloken/Lailloken-UI#417]
Win+Space conflicts with Windows PowerToys run-dialogue hotkey.

**Comment by Lailloken** [comment]
Oh, I see. Thanks for the heads-up, I will do that for today's release.

You can manually remove/change it in the meantime by editing these lines at the very end of `modules\hotkeys.ahk`:
```
RWin & Space::
LWin & Space::
Reload
ExitApp
```

**Comment by velit** [comment]
You're awesome! Thanks! :)

**Comment by Lailloken** [comment]
[v1.54.4](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.54.4) is now live and includes customization of that hotkey-combination. I'll leave this thread open for now, in case something else comes up.
