### ISSUE TITLE
Extra '|' at end of regex breaks it

### ISSUE THREAD

**Issue by FanghanHu** [Lailloken/Lailloken-UI#42]
using the available burn mods function and the query was `^(has|bom|con|dro|sha|ste|blo|stormwe|)` with an extra '|' after stormwe, causing it to highlight everything.
![image](https://user-images.githubusercontent.com/3207447/156934251-5d75f90f-ca22-4816-b320-4ae002085eb3.png)

**Comment by Lailloken** [comment]
Just released a new version with a fix the moment you posted this :D

**Comment by FanghanHu** [comment]
<3
