### ISSUE TITLE
Error when clicking on Lailloken UI.ahk

### ISSUE THREAD

**Issue by LordStorm7** [Lailloken/Lailloken-UI#420]
![2024-07-26 (6)](https://github.com/user-attachments/assets/2a808b71-ee9c-4c5b-9177-9ab16b81b4d1)

**Comment by Lailloken** [comment]
That usually happens when the ZIP-file wasn't extracted correctly, or when you're trying to open the tool from within the ZIP-file. You need to extract the Lailloken-UI folder and save it on your PC first.

**Comment by heinrich6745** [comment]
> That usually happens when the ZIP-file wasn't extracted correctly, or when you're trying to open the tool from within the ZIP-file. You need to extract the Lailloken-UI folder and save it on your PC first.

I did exactly this to make sure it was extracted correctly and opened it outside the zip and i am still having this error, not sure why it is appearing currently preventing me from using it
