### ISSUE TITLE
Black screen when trying to enable tldr tooltips

### ISSUE THREAD

**Issue by meister0** [Lailloken/Lailloken-UI#421]
Hey, I got a black screen when trying to enable tldr tooltips. Any ideas how to fix?

![image](https://github.com/user-attachments/assets/ffc3014e-3e65-4cfb-aacc-9337aa2630e0)

**Comment by Lailloken** [comment]
Are you on Windows 11? Ever since GGG updated the render-engine, there has been an incompatibility with taking screen shots. The screen will flash black for a split-second. Switching to DX12 in game usually fixes that.
