### ISSUE TITLE
Labyrinth trials ruin map tracking

### ISSUE THREAD

**Issue by Pegoth** [Lailloken/Lailloken-UI#425]
Entering a trial mid map counts as you entering a new map, so the map tracker asks for kill count and on the end it will look like I did the same map twice.

I think you should make trials as map extra stuff like league mechanics.

There are 6 zones (with loading screen, so you get the same entering message as a new zone):

```
Trial of Piercing Truth
Trial of Swirling Fear
Trial of Crippling Grief
Trial of Burning Rage
Trial of Lingering Pain
Trial of Stinging Doubt
```

Example log:

`2024/07/27 18:13:38 17607968 cff94598 [INFO Client 10612] : You have entered Trial of Piercing Truth.`

**Comment by Lailloken** [comment]
Thanks for reporting, this is a bug and not intended. I'll look into it.

**Comment by Lailloken** [comment]
v1.54.4 (Hotfix 2) is now live and should fix this issue. Sorry about the inconvenience.

**Comment by Pegoth** [comment]
@Lailloken Thanks for the quick fix, I'll started a new character so it'll take a while before I can test it.

**Comment by Pegoth** [comment]
Seems to be working correctly now. Closing the issue.
