### ISSUE TITLE
Cheat-sheets

### ISSUE THREAD

**Issue by Wynadorn** [Lailloken/Lailloken-UI#428]
Hey, I was wondering if the cheat sheets feature is currently working.
I cannot get it to display an image.

for example:
```
[general]
enable=1
type=images
image search=static
activation=hold
[UI]
scale=1
position=2,2
[image search]
last coordinates=1406,973,110,37
```

![image](https://github.com/user-attachments/assets/701090af-f776-42c8-9ad4-93c4c641d9bd)

When pressing the checkbox to enable/disable the cheatsheet it'll remain checked, might be a clue in fixing
![image](https://github.com/user-attachments/assets/58726c78-cf83-439e-a5f3-64b3b6a03b1e)

I've tried different omi-keys, `default`, `END`, `L`, different modifies nothing seems to show the image.
 - Calibration / Test seems to work fine.
 - Static / Dynamic screen checks don't seem to make a difference
 - Hold / toggle activation doesn't seem to make a difference 
 - The manage image file buttons Paste, Snip, Show and Delete work fine, and show is able to show an image.

![image](https://github.com/user-attachments/assets/ed25471d-f9b8-473c-9358-a6e8539dd0eb)

Could anyone let me know if it's working for them in 1.54.4?

**Comment by Lailloken** [comment]
Tested it right now, and it seems to be working:
![image](https://github.com/user-attachments/assets/b9180171-601f-47c5-a342-a6bddf740204)
***
![image](https://github.com/user-attachments/assets/61fca0c5-1bf2-46ad-ab83-8d53762f2536)
***
![image](https://github.com/user-attachments/assets/5b826493-8df1-433c-805d-fb27187957ce)

**Comment by Wynadorn** [comment]
Hm not sure what fixed it but it's working now, maybe switching to the unicode version of ahk fixed the issue.
