### ISSUE TITLE
Lailloken changes my game-window on Super Ultrawide

### ISSUE THREAD

**Issue by AAUCrisp** [Lailloken/Lailloken-UI#437]
When I start _Lailloken UI_ while playing _PoE_, or if it's already running when I boot up _PoE_, my game window gets changed.

_PoE_ generally does not support Super Ultrawide...
The 5120x1440 resolution is there as an option, but it just adds black bars at the sides (they've said it's because of server limitations on game logic too far away from the player.
Not that this matters anyway... I still use the 5120x1440 resolution.

But... when _Lailloken_ is started, the game window changes into 16:9 format (and resolution) and without black bars, making it into a _Borderless Windowed_ mode instead of the _Fullscreen Windowed_ that the game officially supports... meaning that my desktop i visible besides the game window.

It's a nice enough option to have I guess... but since I'm on an OLED, I'd prefer not having static desktop things more than I need to.

Not to mention... it's not even keeping my chosen resolution, it goes the usual 16:9 1440p resolution.

To fix the problem and get it back to the right window-mode and resolution, I literally just have to choose a different window mode (usually take _Windowed_) and tell it to _Revert_ when it asks if I wanna keep my change.
So it knows what it's supposed to be, it's just... acting weird.

As far from everyone has a Super Ultrawide, I'd be glad to run tests for you, if needed.

**Comment by Lailloken** [comment]
I need to do some testing, it's possible the recent introduction of dedicated render-resolution settings in game might have changed how the client-window reacts to being moved/resized by external tools. I have received a few reports of weird resizing behavior.

This behavior is not intended. On first launch, the tool merely checks the current client-window resolution and whether it's compatible. It really should do any resizing by itself.

For the time being, you can edit `ini\config.ini` in notepad and add/edit these lines under `[settings]`:
```
custom-width=5120
custom-resolution=1440
```

My tool has a toggle in the `general` section of the settings menu to take black bars in Super-UltraWide mode into account and offset overlays accordingly. You have to make sure this toggle is enabled once everything else is running correctly.

**Comment by AAUCrisp** [comment]
**Update**
As I couldn't see the option for "_Client has black bars on the side_", I tried setting the vertical resolution in the UI to a different one, and return it to 1440... 

It then.... did things... and now the "black bar option" is there, and my game does not act weird when booting it (or _Lailloken UI_)

Never even godt around to adding the resolution in the _config.ini_.

Maybe that'll help your troubleshooting :)
Guess it's some sort of check that maybe should happen, so it's properly "resets" screen-settings when people upgrade their monitors (last league I played, I was on a "normal" 2560x1440

Even if my issue hadn't been fixed already... thank you for an amazing tool 😋

**Comment by Lailloken** [comment]
Okay, now that makes sense. You should have mentioned that you're not a first-time user and that you've switched monitors.

Your issue is caused by an oversight that I'm going to fix for the next release: The tool is applying the last-known working resolution at startup, even in windowed fullscreen. I will change it so it only applies the vertical resolution, not both.
