### ISSUE TITLE
Item Info tooltip: shift click identifying & crafting not working properly

### ISSUE THREAD

**Issue by ksenanayaka** [Lailloken/Lailloken-UI#440]
Have been using this tool for a while, and have encountered this issue a few times, but this league a lot. When shift + using crafting currency like essence, the tooltip updates, but always shows the previous affixes instead of the new ones. Identifying shows an empty overlay window instead of the affixes. I have set the inventory check and the normal middle click works fine, but the shift-click is mostly not working for me.

**Comment by Lailloken** [comment]
This was also raised in #431.

My first suspicion was server-load during high-traffic hours, but the user found something else that was interfering. Could you check if you have the same issue or whether shift-clicking improves when server-traffic is usually lower?

**Comment by ksenanayaka** [comment]
I checked for similar open ones but didn't notice it as it was closed. That could be the case. I think during rush hours this is happening. Similar to that OP, I only have PoE Overlay as a tool, but it doesn't have any tooltip-related features enabled. So I don't think it affects this case probably.

**Comment by Lailloken** [comment]
I will improve it for the next release, which will probably come out tomorrow.

**Comment by ksenanayaka** [comment]
Awesome! Thanks for the awesome tool. GL!
