### ISSUE TITLE
Needed a reminder for mandatory actions user must take to regain access to certain feature

### ISSUE THREAD

**Issue by AmaneRin** [Lailloken/Lailloken-UI#444]
I updated from 1.54.5 straight to 1.54.7, was wondering why my omni-key isn't working at all.
Then I took a quick glimpse of the changelog noticing that in 1.54.6 users must recal the inventory pixel-check.

So I was thinking if there be any chance, that when an update implements some sort of fixes or anything else, which requires users to perform certain action to gain/regain access to a feature of the script, there would be some kind of reminder that notifies the user to do so?

**Comment by Lailloken** [comment]
The updater includes a summary of changes for every release, and I generally expect users to read them before updating:

![image](https://github.com/user-attachments/assets/e6c39daa-f862-41f4-8349-e7ff85e957bb)

But yes, your suggestion is still valid, and I have actually shown update-messages like that in the past. It just slipped my mind this time.
