### ISSUE TITLE
Item rarity and monster pack size are inverted in "Highlight map rolls" feature

### ISSUE THREAD

**Issue by azais-corentin** [Lailloken/Lailloken-UI#447]
Hello, on version 1.54.7, it seems the input boxes for item rarity and monster pack sizes are inverted.

Here are some screenshot demonstrating the inversion on the same map:

Setting rarity threshold to 30 highlights the 31% pack size:
![image](https://github.com/user-attachments/assets/2e3c78f8-a2b1-4eb5-9a70-f7a255e2bcdc)

Setting pack size threshold to 35 highlights the 49% rarity:
![image](https://github.com/user-attachments/assets/40efb6a5-2e26-4c42-bdfe-147342201dba)

**Comment by Lailloken** [comment]
Huh, you're right. Thanks for reporting, I'll fix asap.

**Comment by Lailloken** [comment]
Fixed in v1.54.7 (Hotfix 1)
