### ISSUE TITLE
Suggestion: Ignore list for burnrecipes

### ISSUE THREAD

**Issue by Xebtria** [Lailloken/Lailloken-UI#45]
Example: My build absolutely cannot run drought bringer.
With the new autoscanner I want to prevent accidentally doing drought bringer recipe as a burn recipe.
While the recipe itself would not kill me, but I would need to manually delete drought bringer from the inventory (as I would never add it to a monster), and I want to prevent that from happening in the first place..

**Comment by Lailloken** [comment]
Very good idea. I'll add a blacklist that prevents recipes from being suggested as burners.

**Comment by Lailloken** [comment]
Suggestion implemented in v1.22.2
