### ISSUE TITLE
[Solved | Developers plz check the solution] Map Tracker's Loot Tracking doesn't work

### ISSUE THREAD

**Issue by GoodCharles** [Lailloken/Lailloken-UI#462]
Hello and first of all, I'm quite new to Lailloken-UI.

Version: 1.55.1
I've done the Screen-Checks and tested them to receive the green "Positive" tooltip.
My resolution is 1920x1080
I've checked if Lailloken-UI is able to read my files and the test results all comes back "OK"

Everything else regarding the Map Tracker feature works as intended except the Loot Tracking _(which is the main reason I'd like to use the feature)_

I hold down CTRL and Left Click on an item (Chaos Orb) to transfer it to my stash but the Window with my Map name doesn't generate/read the items and doesn't display it below the Map name as shown in the official Github guide/wiki example.

I'm willing to troubleshoot and give out any info as needed.

The image below is after a map. I'm in hideout. I transferred a Gemcutter's Prism and a Chaos Orb as a test.

![image](https://github.com/user-attachments/assets/a4d0d2d3-1658-49b0-93e1-202aeda1ab18)

![image](https://github.com/user-attachments/assets/4aad00ac-be36-4bfc-a711-a2271f965883)
Output Dialogue is enabled as per Lailloken Requirements

# SOLVED;

Problem: If Stash-Ninja is not enabled, the Stash-Check option is not visible
![image](https://github.com/user-attachments/assets/e74c5782-b6db-4cbd-b013-46c60ebe6311)

Now I have enabled Stash-Ninja, and the Screen-Checks is RED;
![image](https://github.com/user-attachments/assets/02bf81ec-49e5-43ab-a92d-b4c2b09dc2da)

Clicking RED Screen-Checks shows us a whole new Screen Check, Stash-Check;
![image](https://github.com/user-attachments/assets/a8dc94e0-f36b-4cc4-8aae-09be5bc2efaa)

AND now everything works as intended !!
![image](https://github.com/user-attachments/assets/d9b76ea6-e045-43e2-a0df-5213d20161da)

# This problem can be avoided if Lailloken-UI unlocks the Stash-Check in the Screen-Checks tab if we enable Map-Tracking or Loot-Tracking

**Comment by Lailloken** [comment]
Oh, sorry about that. It's an oversight in how it handles the image-check list, resulting in the "stash" image-check and the "stash-ninja" feature being linked unintentionally. I'll fix it shortly.

**Comment by Lailloken** [comment]
Fixed in [v1.55.1 (Hotfix 1)](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.55.1). Thanks for reporting.

**Comment by GoodCharles** [comment]
You are awesome @Lailloken !
I feel lucky to have discovered your UI and happy if I could provide helpful feedback! =)
