### ISSUE TITLE
Crash if inserting items into stash too fast while Loot-Tracking is on

### ISSUE THREAD

**Issue by GoodCharles** [Lailloken/Lailloken-UI#463]
![image](https://github.com/user-attachments/assets/33167bd0-50ae-419a-86a2-c9fa0df9d9ac)

Not sure what it all means as I'm not familiar with coding but it happens sometimes if I stash many items very quickly.

Version: 1.55.1
Normal PoE Client from website
Resolution: 1920x1080
Using Loot-Tracking within Map-Tracker

**Comment by GoodCharles** [comment]
![image](https://github.com/user-attachments/assets/5e928b47-045a-495c-a698-7ed412171f58)
Just got another one so I thought more data = better understanding !

**Comment by Lailloken** [comment]
Thanks for reporting this. I can't replicate it on my end, but from the error-message it seems to be a timing-issue between flashing the panel (to signal kill-count refresh) and adding an item to the list. I'll include a potential fix in a hotfix-release shortly.

**Comment by Lailloken** [comment]
[v1.55.1 (Hotfix 1)](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.55.1) includes a potential fix for that. Before applying color to the panel to make it flash, it now checks if the panel can be addressed first.

I'll leave this thread open for now in case something else comes up.
