### ISSUE TITLE
English - Detected Language: Not supported

### ISSUE THREAD

**Issue by Volteus** [Lailloken/Lailloken-UI#468]
I have both chat language and language option set to English in UI part of game options. However, Lailloken-UI says something otherwise and dectects my language as unspported disallowing me usage of any cool features because of this. 
![2024-09-02_19h36_15](https://github.com/user-attachments/assets/42908e21-0501-4aa8-a762-703bb9cd4dca)
![2024-09-02_19h36_31](https://github.com/user-attachments/assets/e6ae89d0-a3c7-4a82-96da-01cb26a8a92e)

(Unless English is not supported, which I cannot belive for)

**Comment by Lailloken** [comment]
Do you have local chat disabled?
![image](https://github.com/user-attachments/assets/bba94c15-e891-4d2d-a602-027dc4a9bf07)

The tool uses the client.txt log-file created by the game to determine the current language-settings (by looking for "you have entered XYZ"). If local chat is disabled, these messages will not be logged.

If it is indeed disabled, enable it and waypoint-travel between a few locations before restarting the tool.

**Comment by Volteus** [comment]
Sadly, it did not help. Yes, I had at first disabled local chat, but after enabling it, waypoint-traveling between a few locations and restarting the tool nothing has changed. Also, I've noticed that my Client.txt file in logs folder has ~7 GB of size

**Comment by Volteus** [comment]
Long story short, deleting oversized Client.txt resolved issue xD
