### ISSUE TITLE
Heyo, thanks for the bookmark feature, but regex coming out too long to paste

### ISSUE THREAD

**Issue by Nchi** [Lailloken/Lailloken-UI#469]
hit 50 char limit with ^(.*bloodlines|.*hordes|.*monstrous.lineage|.*wisps)$

I wonder if there is a open regex solver type thing to shorten it computationally lol. rather where to find it since it definitely exists with how evil regex is. Thanks again! now I just gotta get steam to record the tool with the game next lool

was shortening by hand and I am not sure what ^ and $ do in regex off hand but i had to delete them to get it to work 

.*bloodlines|.*hordes|.*monstrous.lineage|.*wisps

but both wisp scarabs show up, and with their names its... inconvenient to regex im sure with the limit.            

well I cant figure out how to do something like wisp not ritual, but I realized I was avoiding the flavor text, when its the issue anyway! so I could just use that .... and violina- "ocht con" for scarab of wisps, "rit.*wisp" for ritual scarab of wisps. terrible to upkeep if they changed flavor texts often but I dont think thats likely, moreso just the scarabs themselves changing lol. 

ugh I deleted some stuff apparently,  but ho.*od for bloodlines since it pulls up the lineage one from the flavor text..  I went and bought the two scarabs I was missing so I could test better.. really should just look up a solver lmao

ok for this set of regex at least...

"ho.*od|hordes|us lin|cht con"

fun times of over focusing on random stuff instead of farming! let me know what you find if you look into a solver, I can pluck away at this by hand over time its not too bad fun wise and regex do be a useful skill.... Ill make sure to keep it away from stuff that could knock commerce down globally though dw.

**Comment by Lailloken** [comment]
The regex is specifically for the in-game exchange since that is seemingly not as restricted as other in-game searches.

**Comment by Nchi** [comment]
oh wild I figured it would be the same char limit. It still has the two wisp scarab overlap but nbd if intent was never for stash anyway- exchange is much easier to tell what you are grabbing with the text right there lol
