### ISSUE TITLE
Cannot Load Recombination Module

### ISSUE THREAD

**Issue by DeckStarg** [Lailloken/Lailloken-UI#476]
Have update 1.54.6 but recombination module won't loadd on startup.  I try to launch the AHK file from the modules folder and I get an error.
![Capture](https://github.com/user-attachments/assets/92708042-f912-4438-a3ac-c6ad1985dfb2)

**Comment by Lailloken** [comment]
You can't launch modules individually. You have to launch the `Lailloken UI.ahk` file in the main folder, and the tool will run in the background while PoE is open. Here's a [quick-start/setup guide](https://github.com/Lailloken/Lailloken-UI/wiki), and most features also have their own entry in the wiki (sidebar on the right).

**Comment by DeckStarg** [comment]
Yeah I did that but it wasn't loading into the main UI, hence I tried to launch it to "add" it to the UI.
![Capture](https://github.com/user-attachments/assets/7da6d7ed-6859-4796-ad90-78eb784fa6f3)

**Comment by Lailloken** [comment]
The recombination simulator doesn't have its own settings section because the feature is rather simple and doesn't need it. This is mentioned in the [wiki](https://github.com/Lailloken/Lailloken-UI/wiki/Recombination-Simulator), and it also explains how to use the feature.

**Comment by DeckStarg** [comment]
Thank you.  I finally got it to work but I don't see any of the NNN, EXCL or DESIRED BASES check boxes.

Any ideas?

**Comment by Lailloken** [comment]
You're running an older version (v1.54.6), which I missed earlier. You can use the built-in updater to get the latest version.
