### ISSUE TITLE
Item info broken due to other AHK script

### ISSUE THREAD

**Issue by ksenanayaka** [Lailloken/Lailloken-UI#477]
I tried using the logout macro script LutTools simultaneously with this script and all other features work, except the item info panel. It just does not pop up. I tried changing the omni-key and it still does not work. When the other script is closed, it works fine. It does not seem that they use the "C" key or "Middle Mouse", in their script, which could potentially cause an issue. I would appreciate any advice or help you can give.

- I am using Windows 10
- I use DX12 as well
- I have set up the inventory screen checkup

Attaching their hotkey screen just in case.

![image](https://github.com/user-attachments/assets/4096e6be-e3c2-4490-bbb0-5bec5bb45839)

**Comment by Lailloken** [comment]
Thanks for reporting this incompatibility. I can't test these issues myself, so could you check whether:
- it makes a difference which tool you start first

- the context-menu on items works (omni-clicking gear, for example) while both are running

- the clipboard changes when you omni-click an item (it should be cleared when omni-clicking items, and then contain the item's tooltip-text)

**Comment by ksenanayaka** [comment]
1. The order in which the scripts are opened doesn't matter.
2.

**Comment by Lailloken** [comment]
The third point indicates that LutTools is somehow either interfering with the clipboard or preventing my tool from copying the item tooltip-text in the first place.

Is that tool still being maintained? I can't find a repo nor up-to-date info.

**Comment by ksenanayaka** [comment]
There is no GitHub repo I think. Tool page is <details> <summary>URL</summary> http://lutbot.com/#/ </details> But I don't know if it's properly maintained. It's a long shot anyways. I think I'll make do with a normal logout macro from your tool. Thanks for looking into this.

**Comment by ksenanayaka** [comment]
Managed to find the issue @Lailloken. The LutTools had a small overlay that failed the screen check for inventory and didn't show the tooltip. I just wanted to let you know. Thanks again for the awesome tool!
