### ISSUE TITLE
Leveling-tracker not showing up

### ISSUE THREAD

**Issue by Leafiam** [Lailloken/Lailloken-UI#484]
i might be daft, but i have tried everything  i can think of to get this working. 
Re installed everything and followed every guide to the best of my abilites. 
Please help.

![image](https://github.com/user-attachments/assets/40fd97f4-f383-4e4d-9be6-db8b6e4c413a)

**Comment by Lailloken** [comment]
Oh, I didn't get that you meant the settings tab, not the feature itself. I renamed the feature from "leveling tracker" to "act-tracker" a while ago, just to emphasize it's a campaign-related feature -- the old name could potentially be interpreted as a feature that keeps track of how fast you're leveling or something.

I hope you get well soon.

**Comment by Leafiam** [comment]
oooooh! Okey that makes a lot of sense! ill keep tinkering with the settings then. 
Thanks again for the quick reply and well wishes!
