### ISSUE TITLE
[INFO] Upcoming game updates with archnemesis UI changes

### ISSUE THREAD

**Issue by Lailloken** [Lailloken/Lailloken-UI#5]
GGG has announced archnemesis UI changes for the near future, including permanent recipe indicators (colored frames). This should not affect this tool in any way. If more aspects of the UI get changed, the tool may not work immediately after the update is published. If that is the case, there may be some hours of downtime for this tool since game updates usually come out at while I'm sleeping.

I'm asking you to keep this in mind and keep issues submissions to a minimum -- check if there already is a submission and confirm the issue in the comments. If you want to be even more helpful, you can try to summarize what changed in the UI so that I can adapt the tool even faster in the following morning.

In the unlikely event that GGG increases inventory capacity or changes the fundamentals of the inventory, adaption will of course take longer. I would also take this opportunity to update the scanning method, which would entail re-training on your end.

**Comment by kharom1** [comment]
Hey i should propably create new thread but i dont think its worth it for problem that small https://i.imgur.com/d8Dn6DF.jpg is this possible for this red cursor to be like it should ? in the middle ? im using 1080 an was waiting for an update but i never came so maybe you could tell me how i can fix it/

**Comment by Lailloken** [comment]
I can change that for the next release. It was just a placeholder from when I started, and then I never touched it again -- that's why it looks so ugly.

**Comment by kharom1** [comment]
> I can change that for the next release. It was just a placeholder from when I started, and then I never touched it again -- that's why it looks so ugly.

i mean even the images in recognition folder looks weird ? im 100% sure that image like that https://i.imgur.com/o0ZVUSN.jpg (echoist) will not work in pixel search or maybe im wrong ?

**Comment by Lailloken** [comment]
I don't know how this could have happened. Which resolution are you running?

**Comment by kharom1** [comment]
https://i.imgur.com/iy3Ghck.jpg

**Comment by kharom1** [comment]
(I was testing previously in windowed fullscreen but couldn't get the overlay to show but after i deleted and unpacked again it worked just now 😂)
Okay now it actually works like it should and its even skipping the already "recognized" images i guess mb for running in windowed thanks for your help, you did an amazing job with that tool ❤
