### ISSUE TITLE
Typo in screen-check menu (incorrect explanation)

### ISSUE THREAD

**Issue by Joh-nnyC** [Lailloken/Lailloken-UI#55]
The instruction for the gamble screencheck also has the syndicate board explanation pasted below it instead of an explanation for gamble

![image](https://user-images.githubusercontent.com/15916010/170043104-c523efd0-c00c-4a50-a286-025b4186f35e.png)

**Comment by Lailloken** [comment]
Thanks, it'll be fixed next release. I even double-checked the tooltips to make sure they're correct >.>, Blindloken strikes again.
