### ISSUE TITLE
Chat macros in other apps no longer work while running this program

### ISSUE THREAD

**Issue by reallemon** [Lailloken/Lailloken-UI#57]
As of version 1.24.4, chat macros in my other apps no longer work. The problem persists in newer versions of the app, but not in version 1.24.3. I am using [SlimTrade](https://github.com/zmilla93/SlimTrade) and [Awakened POE Trade](https://github.com/SnosMe/awakened-poe-trade), and none of the chat macros in either app works. Sometimes it will just open up chat and leave it focused, sometimes it brings up the escape menu instead of doing anything in chat. If I have chat opened and focused, the shortcuts from SlimTrade will work, but not the ones from Awakened POE Trade. The problem is definitely resulting from this program, since it is resolved by closing out the macro.

I suspect the problem is related to the bestiary features that replace typed words, but I can't turn the feature off directly to test my hunch. The problem persists whether or not I've set up image checks for bestiary and regardless of the status of those checks.

**Comment by Lailloken** [comment]
Thank you very much for this detailed report. Your hunch was correct, the bestiary search caused conflicts with macros from other tools. It was a stupid oversight to bind it to the enter-key when I have the omni-key that is specifically designed to prevent conflicts with other tools.

**Comment by reallemon** [comment]
Thank you for the quick response and fix! I really love this tool and appreciate all the work you put in to it!
