### ISSUE TITLE
Left clicking results in the window flashing for a second and vanishing.

### ISSUE THREAD

**Issue by ExecutedOnce** [Lailloken/Lailloken-UI#7]
Hey posted on Reddit before about the left clicking issue  (tried the 1.1 version and the latest beta), it might be something on my end, this is a pretty minor issue and I usually work around it by just holding right click and clicking the name of the bookmark.

![image](https://user-images.githubusercontent.com/66980182/154404656-587f4c94-bd40-4a23-81a8-00d7ae30b79b.png)
When I click on a bookmark name, the sub-component window flashes for a fraction of a second. The 'clear' button either has a grey or blue selection outline around it.

If (each time I click on a bookmark-name), I click an empty space in the black container box (between bookmark names or to the right of them), then click on the name, they load as intended with holding left click. If I try to click one without doing this, the name just flashes and instantly disappears.

Holding right click down and left click also works. I guess the window tries to grab focus sometime after the bookmark is clicked? 

Also just to add I wouldn't really worry about this unless someone else has issues, it could just be me and holding right click isn't really an issue for me. Just figured I'd post some more information in case it became a widespread issue at some point.

**Comment by Lailloken** [comment]
Thanks for the details. Yes, seems to be a focus issue. The game client sometimes behaves in a weird way, e.g. when you win-D to minimize it, it immediately maximizes whenever you focus another window or panel. The next release will include another attempt to fix that. Should be out today. It's strange this issue is so inconsistent.

**Comment by ExecutedOnce** [comment]
Same thing with 1.15.2-beta. But It really might just something weird on my end at this point and It doesn't really impact me anyway.  

Also btw not sure if you intentionally or unintentionally left out the icons, just in case it was accidental the "img\Archnemesis Icons\" directory+icons haven't been added to the 1.15.2 -beta.

**Comment by Lailloken** [comment]
Thanks for the heads-up, totally missed that. Still getting used to this GitHub business, lol. What kind of mouse are you using? It seems the script doesn't recognize your click as a regular left-button click.

**Comment by ExecutedOnce** [comment]
So with the code like that, the middle two recipes (brine/shakari) generally work and the end two still flash and disappear, which is really odd.
![image](https://user-images.githubusercontent.com/66980182/154664881-76f64a5b-5afd-4b64-9168-44b4e08a81ad.png)

**Comment by Lailloken** [comment]
Try replacing the KeyWaits with a while-loop:
```
while GetKeyState("LButton", "P") 
sleep, 100
```
It should be functionally the same but may improve things.
