### ISSUE TITLE
UI Change after patch 3.17.1

### ISSUE THREAD

**Issue by MortuusPat** [Lailloken/Lailloken-UI#9]
First of all let me say... What an amazing overlay you've made. Thank you so much for it.

Now. GGG did some improvements with the archnemesis interface and they moved things down a bit to make room for their filtering system. I'm sure you are aware of it, but I still wanted to report it. Basically the overlay doesn't line up anymore.

Again. Thanks for your work.
Have a good weekend.

**Comment by Kimano** [comment]
If anyone wants to fix it themselves, you just need to go in the resolutions.ini file, find your resolution and tweak the yScan and other y values down a bit. I found 20-30 pixels was about right on 2160p

**Comment by MortuusPat** [comment]
Like Kimano said tweaking the y values up by 20 did the trick. (1080p)

**Comment by Lailloken** [comment]
Thanks for the information, peeps. The first update with support for four resolutions is out.

**Comment by MortuusPat** [comment]
Thanks bro.
