### ISSUE TITLE
I start up script nothing happens

### ISSUE THREAD

**Issue by SaddestMan** [Lailloken/Lailloken-UI#94]
**I start up ''Lailloken UI.ahk'' nothing happens, no overlay nothing.
I am on windows fullscreen(1280x720)**

**Comment by Lailloken** [comment]
Try updating your AutoHotkey installation. The script shouldn't exit like that without an error message.

**Comment by Lailloken** [comment]
Are you on the regular PoE-client? Could you also exit the script, start it, then double-click the tray icon and copy the text from the window and paste it here?

**Comment by SaddestMan** [comment]
yeah on ggg client, window text:

---- C:\Users\games\Desktop\Lailloken-UI-1.28.0\Lailloken UI.ahk
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: }
228: if InStr(A_Loopfield, "is now level ")  
236: } (0.02)

and that's it

**Comment by Lailloken** [comment]
Okay, that's some dumb coincidence. You have to go to the logs folder in your PoE installation, open the client.txt and add:
`: character is now level 2` to the end of it.
Make sure to include the colon at the beginning.
Have you recently re-installed PoE? The script is trying to find a recently-played character even though the leveling tracker is not enabled, but it cannot find it in the log file.

**Comment by Lailloken** [comment]
Actually, it's `: character (Scion) is now level 2`

**Comment by SaddestMan** [comment]
can't connect to servers but I don't think it's related to this, but overlay shows up now, thank you!
