### ISSUE TITLE
Overlayke Issues Thread: Bugs, Misrecognition, it can't hecking count, etc.

### ISSUE THREAD

**Issue by Lailloken** [Lailloken/Lailloken-UI#98]
Post any bugs or issues related to Overlayke here. Screenshots with miscalculations would be appreciated.

**Comment by RDELX** [comment]
When I try to scan the tablet it says No calibration data. I tried to calibrate it but it said "Calibrating..." and nothing else.

![PathOfExileSteam_szg7fNR8Bx](https://user-images.githubusercontent.com/51673029/187263491-8fa15dae-99d3-41e4-b225-274758651921.jpg)

![PathOfExileSteam_7UBpu1frga](https://user-images.githubusercontent.com/51673029/187263935-9132594f-5cc0-4632-b317-f22898d65c8f.jpg)

**Comment by Lailloken** [comment]
Did you screen-cap a single water tile or something larger (with the snipping tool)? There shouldn't be anything to get stuck on, but it may take very long if you screen-cap an image that's too large pixel-wise. You could check task manager to see if AutoHotkey has high CPU usage. If not, the script could indeed be stuck on something.

**Comment by Lailloken** [comment]
I'll be offline soon (sleep), so there won't be any response for a few hours. If it's still not working for you, here are some steps that may help:
- restart the script, open the overlayke section in the settings menu, and click reset
- calibrate again but this time with a very small screen-cap (just as a test because it should finish quickly)
- if it still gets stuck, you could try updating AutoHotkey
- when restarting the script, does the it load the hotkey you set correctly? If not, the script may not have write permissions to save the config for some reason

The calibration code is quite simple and I can't think of anything that would make it behave as if stuck, so something outside the script has to be the issue.
